/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistejm.telas;

import br.com.sistejm.classes.Agendamento;
import br.com.sistejm.classes.Conexao;
import br.com.sistejm.classes.Configuracoes;
import br.com.sistejm.classes.Mediuns;
import br.com.sistejm.classes.Relatorios;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.util.Calendar;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Michel
 */
public class DAgendamento extends javax.swing.JDialog {

    Agendamento ag;
    Calendar cal;
    Mediuns med;
    Configuracoes config;
    Conexao con;
    Relatorios rel;
    
    private String tconsultado;
    private String consultor;
    private int codusuario;
    private String codAgendamento;
    private String pago;
    private String user;

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getPago() {
        return pago;
    }

    public void setPago(String pago) {
        this.pago = pago;
    }

    public String getConsultor() {
        return consultor;
    }

    public void setConsultor(String consultor) {
        this.consultor = consultor;
    }

    public String getCodAgendamento() {
        return codAgendamento;
    }

    public void setCodAgendamento(String codAgendamento) {
        this.codAgendamento = codAgendamento;
    }
    
    public String getTconsultado() {
        return tconsultado;
    }

    public void setTconsultado(String tconsultado) {
        this.tconsultado = tconsultado;
    }

    public int getCodusuario() {
        return codusuario;
    }

    public void setCodusuario(int codusuario) {
        this.codusuario = codusuario;
    }
    
    
    
    
    /**
     * Creates new form DAgendamento
     */
    public DAgendamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ocultaId(false);
        limpaCampos();
        ocultaComboMedium(false);
        preencheComboMedium();
        preencheTabAgendamento();
        boasVindas();
        preencheQuantidade();
    }
    
    public void fechar(){
        this.dispose();
    }
    
    public void boasVindas(){
        preencheTexto("Bem-vindo ao agendamento");
        preencheTexto("=============================");
        preencheTexto("Aqui serão registrados as consultas com o Caboclo ou Exu.");
//        this.setConsultor("Caboclo");
//        this.setPago("S");

    }
    
    public void recebeUsuario(int iduser, String nomeUser){
        this.codusuario = iduser;
        this.user = nomeUser;
        
    }
    
    public void preencheComboMedium(){
        med = new Mediuns();
        med.preencheComboMedium(comboMedium);
    }
    
    public void preencheTabAgendamento(){
        ag = new Agendamento();
        ag.preencheTabAgendamento(tabelaAgendamento);
    }
    
    public void ativaTextNome(boolean valor){
        txtNome.setEnabled(valor);
    }
    
    public void ocultaComboMedium(boolean valor){
        comboMedium.setVisible(valor);
    }
    
//    public void mudaCorStatus(){
//        labelStatus.setForeground(Color.red);
//    }
    
    public void limpaCampos(){
//        this.setTconsultado("N");
        labelSemana.setText("Aguardando...");
        txtCodigo.setText("");
        txtData.setText("");
        txtValor.setText("");
        txtNome.setText("");
        ativaTextNome(true);
        radioNMedium.setSelected(true);
        comboMedium.setVisible(false);
        txtId.setText("");
        txtData.requestFocus();
    }
    
    public void preencheQuantidade(){
        ag = new Agendamento();
        config = new Configuracoes();
        
        String data1 = config.retornaFormatoDataSQL(config.retornaDataMesAnterior());
        String data2 = config.retornaFormatoDataSQL(config.retornaData());
        
        
        ag.retornaQuantidade(labelValorQuant, data1, data2);
    }
    
    public void ocultaId(boolean valor){
        txtId.setVisible(valor);
        btGerar.setVisible(valor);
        txtConsCodigo.setVisible(valor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        buttonGroupConsultor = new javax.swing.ButtonGroup();
        buttonGroupPago = new javax.swing.ButtonGroup();
        txtData = new javax.swing.JFormattedTextField();
        labelData = new javax.swing.JLabel();
        panelDown = new javax.swing.JPanel();
        labelVersao = new javax.swing.JLabel();
        panelTop = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        btExcluir = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        btGerar = new javax.swing.JButton();
        txtConsCodigo = new javax.swing.JTextField();
        labelConsulta = new javax.swing.JLabel();
        radioMedium = new javax.swing.JRadioButton();
        radioNMedium = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        labelValor = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoTexto = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaAgendamento = new javax.swing.JTable();
        comboMedium = new javax.swing.JComboBox<>();
        labelSemana = new javax.swing.JLabel();
        labelCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        radioCaboclo = new javax.swing.JRadioButton();
        radioExu = new javax.swing.JRadioButton();
        txtValor = new javax.swing.JTextField();
        radioSim = new javax.swing.JRadioButton();
        radioNao = new javax.swing.JRadioButton();
        labelPago = new javax.swing.JLabel();
        labelQuantidade = new javax.swing.JLabel();
        labelValorQuant = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        btBaixa = new javax.swing.JButton();
        btSobe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtData.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtData.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtData.setPreferredSize(new java.awt.Dimension(6, 25));
        txtData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDataKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDataKeyReleased(evt);
            }
        });

        labelData.setText("Data:");

        panelDown.setBackground(new java.awt.Color(255, 255, 255));
        panelDown.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        labelVersao.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        labelVersao.setText("SISTEJM - Versão 1.0 - Interna");

        javax.swing.GroupLayout panelDownLayout = new javax.swing.GroupLayout(panelDown);
        panelDown.setLayout(panelDownLayout);
        panelDownLayout.setHorizontalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDownLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVersao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDownLayout.setVerticalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelVersao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelTop.setBackground(new java.awt.Color(255, 255, 255));
        panelTop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTitulo.setText("Agendamento (Consultas)");

        btExcluir.setBackground(new java.awt.Color(255, 255, 255));
        btExcluir.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/botaoexcluir.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setToolTipText("Excluir");
        btExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btSalvar.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/fileSave.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setToolTipText("Salvar");
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btCancelar.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/cancelar.png"))); // NOI18N
        btCancelar.setText("Sair");
        btCancelar.setToolTipText("Cancelar");
        btCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        txtId.setEditable(false);
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btGerar.setBackground(new java.awt.Color(255, 255, 255));
        btGerar.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        btGerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/icon16x16Relatorio.png"))); // NOI18N
        btGerar.setText("Relatório");
        btGerar.setToolTipText("Relatório");
        btGerar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btGerar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarActionPerformed(evt);
            }
        });

        txtConsCodigo.setEditable(false);

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addGap(18, 18, 18)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtConsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTopLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btSalvar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGerar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        labelConsulta.setText("Consulta com:");

        buttonGroup.add(radioMedium);
        radioMedium.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        radioMedium.setText("Médium da casa");
        radioMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMediumActionPerformed(evt);
            }
        });

        buttonGroup.add(radioNMedium);
        radioNMedium.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        radioNMedium.setSelected(true);
        radioNMedium.setText("Não é médium da casa");
        radioNMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNMediumActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        labelNome.setText("Nome:");

        txtNome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelValor.setText("Valor:");

        campoTexto.setEditable(false);
        campoTexto.setColumns(20);
        campoTexto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        campoTexto.setForeground(new java.awt.Color(0, 0, 204));
        campoTexto.setRows(5);
        jScrollPane2.setViewportView(campoTexto);

        tabelaAgendamento.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tabelaAgendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaAgendamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAgendamentoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaAgendamento);

        comboMedium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboMediumMouseClicked(evt);
            }
        });

        labelSemana.setText("Aguardando...");

        labelCodigo.setText("Comprovante:");

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigo.setBorder(null);

        buttonGroupConsultor.add(radioCaboclo);
        radioCaboclo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        radioCaboclo.setSelected(true);
        radioCaboclo.setText("Caboclo");
        radioCaboclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCabocloActionPerformed(evt);
            }
        });
        radioCaboclo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                radioCabocloKeyReleased(evt);
            }
        });

        buttonGroupConsultor.add(radioExu);
        radioExu.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        radioExu.setText("Exu");
        radioExu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioExuActionPerformed(evt);
            }
        });

        txtValor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtValor.setPreferredSize(new java.awt.Dimension(6, 25));
        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorKeyPressed(evt);
            }
        });

        buttonGroupPago.add(radioSim);
        radioSim.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        radioSim.setSelected(true);
        radioSim.setText("Sim (S)");
        radioSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSimActionPerformed(evt);
            }
        });

        buttonGroupPago.add(radioNao);
        radioNao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        radioNao.setText("Não (N)");
        radioNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNaoActionPerformed(evt);
            }
        });

        labelPago.setText("Pago?");

        labelQuantidade.setText("Quantidade Geral (últimos 30 dias):");

        labelValorQuant.setText("Aguardando...");

        labelStatus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelStatus.setForeground(new java.awt.Color(0, 153, 0));
        labelStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelStatus.setText("Status");

        btBaixa.setBackground(new java.awt.Color(255, 255, 255));
        btBaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/Oks16x16.png"))); // NOI18N
        btBaixa.setText("Atendido");
        btBaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBaixaActionPerformed(evt);
            }
        });

        btSobe.setBackground(new java.awt.Color(255, 255, 255));
        btSobe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/baixa16x16.png"))); // NOI18N
        btSobe.setText("Não atendido");
        btSobe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSobeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioNMedium)
                        .addGap(18, 18, 18)
                        .addComponent(radioMedium))
                    .addComponent(comboMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCodigo)
                        .addGap(35, 35, 35)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelConsulta)
                        .addGap(18, 18, 18)
                        .addComponent(radioCaboclo)
                        .addGap(18, 18, 18)
                        .addComponent(radioExu))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelData, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelSemana))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPago)
                        .addGap(26, 26, 26)
                        .addComponent(radioSim)
                        .addGap(18, 18, 18)
                        .addComponent(radioNao)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btBaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btSobe, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelQuantidade)
                .addGap(10, 10, 10)
                .addComponent(labelValorQuant)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(labelCodigo))
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelData)
                                    .addComponent(labelSemana))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(labelValor))
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(labelConsulta))
                            .addComponent(radioCaboclo)
                            .addComponent(radioExu))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(labelPago))
                            .addComponent(radioSim)
                            .addComponent(radioNao))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioNMedium)
                            .addComponent(radioMedium))
                        .addGap(7, 7, 7)
                        .addComponent(comboMedium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btSobe, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelValorQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

        ag = new Agendamento();
        con = new Conexao();
        
        if(radioCaboclo.isSelected()){
            this.setConsultor("Caboclo");
        }
        if(radioExu.isSelected()){
            this.setConsultor("Exu");
        }
        
        if(radioSim.isSelected()){
            this.setPago("S");
        }
        if(radioNao.isSelected()){
            this.setPago("N");
        }
        
        if(radioNMedium.isSelected()){
            this.setTconsultado("N");
        }
        if(radioMedium.isSelected()){
            this.setTconsultado("S");
        }
        
        String valorPonto = txtValor.getText().replace(",", ".");

        ag.setData(txtData.getText());
        ag.setConsultado(txtNome.getText());
        ag.setConsultor(this.getConsultor());
        ag.setTConsultado(this.getTconsultado());
        ag.setCodusuario(codusuario);
        ag.setValor(Double.parseDouble(valorPonto));
        ag.setPago(this.pago);
        ag.setSemana(labelSemana.getText());
        ag.setCodigo(txtConsCodigo.getText());
//        ag.setCodigo(ag.codigoAgendamento(txtData, this.tconsultado, consultor));
        
        
        this.setCodAgendamento(ag.codigoAgendamento(txtData, this.tconsultado, consultor));

        txtCodigo.setText(this.getCodAgendamento());
        
        if(!txtId.getText().equals("")){
            ag.setIdagendamento(Integer.valueOf(txtId.getText()));

            if(ag.alterarAgendamento()){
                preencheTexto("Agendamento salvo com sucesso!");
                if(JOptionPane.showConfirmDialog(null, "Deseja imprimir o comprovante ?", "SUCESSO", JOptionPane.YES_NO_OPTION) == 0){
                    rel = new Relatorios();
                    rel.geraComprovanteAtendimento(txtCodigo.getText());
                }
                limpaCampos();
                preencheTabAgendamento();
            }

        }else{
            if(ag.verificaExistente()){
                preencheTexto("Este agendamento é existente. Altere ou exclua para registrar.");
            }else{
                if(ag.incluirAgendamento()){
                    preencheTexto("Agendamento salvo com sucesso!");
                    if(JOptionPane.showConfirmDialog(null, "Deseja imprimir o comprovante ?", "SUCESSO", JOptionPane.YES_NO_OPTION) == 0){
                        rel = new Relatorios();
                        rel.geraComprovanteAtendimento(txtCodigo.getText());
                    }
                    preencheTexto("Código do Agendamento: " + this.getCodAgendamento());
                    limpaCampos();
                    preencheTabAgendamento();
                }
            }
        }

        
        // TODO add your handling code here:
    }//GEN-LAST:event_btSalvarActionPerformed

    public void preencheTexto(String texto){
        campoTexto.setLineWrap(true);
        campoTexto.append("\n" + texto);
    }
    

    
    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        ag = new Agendamento();
        if(!txtId.getText().equals("")){
            if(JOptionPane.showConfirmDialog(null, "Confirma exclusão? ", "Exclusão", JOptionPane.YES_NO_OPTION) == 0){
                ag.setIdagendamento(Integer.valueOf(txtId.getText()));
                if(ag.excluirAgendamento()){
                    preencheTexto("Excluído com sucesso!");
                    limpaCampos();
                    preencheTabAgendamento();
                }
            }
        }else{
            preencheTexto("\nSelecione a agenda para a exclusão");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        fechar();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void radioNMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNMediumActionPerformed

        txtNome.setText("");
        ag = new Agendamento();
        
        ativaTextNome(true);
        ocultaComboMedium(false);
        this.setTconsultado("N");
        txtCodigo.setText(ag.codigoAgendamento(txtData, tconsultado, consultor));

            
    }//GEN-LAST:event_radioNMediumActionPerformed

    private void radioMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMediumActionPerformed
        ag = new Agendamento();
        ocultaComboMedium(true);
        ativaTextNome(false);
        this.setTconsultado("S");
        txtCodigo.setText(ag.codigoAgendamento(txtData, tconsultado, consultor));
        // TODO add your handling code here:igo
    }//GEN-LAST:event_radioMediumActionPerformed

    private void comboMediumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMediumMouseClicked

        txtNome.setText(comboMedium.getSelectedItem().toString());

        // TODO add your handling code here:
    }//GEN-LAST:event_comboMediumMouseClicked

    private void tabelaAgendamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAgendamentoMouseClicked
        String selecaoId = String.valueOf(tabelaAgendamento.getValueAt(tabelaAgendamento.getSelectedRow(), 0));
        String selecaoCodigo = String.valueOf(tabelaAgendamento.getValueAt(tabelaAgendamento.getSelectedRow(), 1));
//        String selecaoAgendamento = String.valueOf(tabelaAgendamento.getValueAt(tabelaAgendamento.getSelectedRow(), 3));
//        preencheTexto("\nCódigo do Agendamento " + selecaoCodigo + " selecionado.");
        txtId.setText(selecaoId);
        txtConsCodigo.setText(selecaoCodigo);
        ag = new Agendamento();
        
        ag.consultaAgendamento(txtId, txtData, txtValor, radioCaboclo, radioExu, radioNMedium, 
                radioMedium, txtNome, txtCodigo, radioSim, radioNao, labelSemana, labelStatus);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaAgendamentoMouseClicked

    private void radioCabocloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCabocloActionPerformed

        this.setConsultor("Caboclo");
        radioNMedium.requestFocus();

        // TODO add your handling code here:
    }//GEN-LAST:event_radioCabocloActionPerformed

    private void radioExuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioExuActionPerformed

        this.setConsultor("Exu");
        radioNMedium.requestFocus();

// TODO add your handling code here:
    }//GEN-LAST:event_radioExuActionPerformed

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btSalvar.setSelected(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased
        ag = new Agendamento();
        if(txtNome.getText().length() > 3){
            txtCodigo.setText(ag.codigoAgendamento(txtData, tconsultado, consultor));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeKeyReleased

    private void txtDataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataKeyReleased

        if(txtData.getText().length() == 2){
            txtData.setText(txtData.getText() + "/");
        }
        if(txtData.getText().length() == 5){
            txtData.setText(txtData.getText() + "/");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataKeyReleased

    private void txtDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataKeyPressed

        config = new Configuracoes();

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(!txtData.getText().equals("")){
                String content = txtData.getText();
                int ano = Integer.valueOf(content.substring(6, 10));
                int mes = Integer.valueOf(content.substring(3, 5));
                int dia = Integer.valueOf(content.substring(0, 2));

                config.retornaSemana(dia, mes, ano, labelSemana);
                txtValor.requestFocus();
            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataKeyPressed

    private void txtValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            radioCaboclo.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorKeyPressed

    private void btGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarActionPerformed

        TelaInicial tela = new TelaInicial();
        this.fechar();
        DRelAgendamento rel = new DRelAgendamento(tela, false);
        rel.setTitle("Relatório de Agendamento | Atendimento");
        rel.setLocationRelativeTo(rel);
        rel.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btGerarActionPerformed

    private void radioSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSimActionPerformed

        this.setPago("");
        this.setPago("S");
        // TODO add your handling code here:
    }//GEN-LAST:event_radioSimActionPerformed

    private void radioNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNaoActionPerformed

        this.setPago("");
        this.setPago("N");
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNaoActionPerformed

    private void radioCabocloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_radioCabocloKeyReleased

        this.setConsultor("Caboclo");

        // TODO add your handling code here:
    }//GEN-LAST:event_radioCabocloKeyReleased

    private void btBaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBaixaActionPerformed
        ag = new Agendamento();
        ag.setCodigo(txtCodigo.getText());
        config = new Configuracoes();
        
        if(ag.alteraBaixaAgendamento()){
            preencheTexto("Comprovante baixado com sucesso!");
            if(JOptionPane.showConfirmDialog(null, "Deseja preencher trabalhos ?", "TRABALHOS", JOptionPane.YES_NO_OPTION)== 0){
                
            }
//            JOptionPane.showMessageDialog(null, "Comprovante baixado com sucesso!");
            config.gravaAtividades("Agendamento | Atendimento", this.user, "Realização da baixa do protocolo " + txtCodigo.getText());
            preencheTabAgendamento();
        }
    }//GEN-LAST:event_btBaixaActionPerformed

    private void btSobeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSobeActionPerformed
        ag = new Agendamento();
        ag.setCodigo(txtCodigo.getText());
        
        if(ag.alteraNBaixaAgendamento()){
            preencheTexto("Comprovante reincluso com sucesso!");
//            JOptionPane.showMessageDialog(null, "Comprovante reincluso com sucesso!");
            config.gravaAtividades("Agendamento | Atendimento", this.user, "Realização da reinclusão do protocolo " + txtCodigo.getText());
            preencheTabAgendamento();
        }
    }//GEN-LAST:event_btSobeActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DAgendamento dialog = new DAgendamento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBaixa;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btGerar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btSobe;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.ButtonGroup buttonGroupConsultor;
    private javax.swing.ButtonGroup buttonGroupPago;
    private javax.swing.JTextArea campoTexto;
    private javax.swing.JComboBox<String> comboMedium;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelConsulta;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPago;
    private javax.swing.JLabel labelQuantidade;
    private javax.swing.JLabel labelSemana;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelValor;
    private javax.swing.JLabel labelValorQuant;
    private javax.swing.JLabel labelVersao;
    private javax.swing.JPanel panelDown;
    private javax.swing.JPanel panelTop;
    private javax.swing.JRadioButton radioCaboclo;
    private javax.swing.JRadioButton radioExu;
    private javax.swing.JRadioButton radioMedium;
    private javax.swing.JRadioButton radioNMedium;
    private javax.swing.JRadioButton radioNao;
    private javax.swing.JRadioButton radioSim;
    private javax.swing.JTable tabelaAgendamento;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtConsCodigo;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
