/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistejm.telas;

import br.com.sistejm.classes.Batismo;
import br.com.sistejm.classes.Coroa;
import br.com.sistejm.classes.Mediuns;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Michel
 */
public class DCoroacao extends javax.swing.JDialog {
    
    Mediuns m;
    Coroa coroa;
    Batismo bat;
    private int dia;
    private int mes;
    private int ano;
    private String selectPadr;

    public String getSelectPadr() {
        return selectPadr;
    }

    public void setSelectPadr(String selectPadr) {
        this.selectPadr = selectPadr;
    }

    public int getDia() {
        return dia;
    }

    public void setDia(int dia) {
        this.dia = dia;
    }

    public int getMes() {
        return mes;
    }

    public void setMes(int mes) {
        this.mes = mes;
    }

    public int getAno() {
        return ano;
    }

    public void setAno(int ano) {
        this.ano = ano;
    }

    /**
     * Creates new form DCoroacao
     */
    public DCoroacao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ocultaText(false);
        this.selectPadr = "";
    }

    public void tabelaMediuns(){
        m = new Mediuns();
        int codemedium = Integer.valueOf(txtCodMedium.getText());
        m.preencheTabNomeMediumRestrito(tabMedium, codemedium);
    }

    public void ocultaText(boolean valor){
        txtCodMedium.setVisible(valor);
        txtCodUser.setVisible(valor);
    }
    
    public void consultaMedium(){
        coroa = new Coroa();
        bat = new Batismo();
        
        bat.setCodMedium(Integer.valueOf(txtCodMedium.getText()));
        bat.consultaBatismoMedium(txtPadrinho, txtMadrinha, txtBatismo);

        coroa.setCodmedium(Integer.valueOf(txtCodMedium.getText()));
        coroa.consultaCoroaMedium(txtCoroacao, txt1Ano, txt3Anos, txt7Anos, txt14Anos, txt21Anos);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        panelTop = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        btCancelar = new javax.swing.JButton();
        txtCodUser = new javax.swing.JTextField();
        txtCodMedium = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        panelDown = new javax.swing.JPanel();
        labelVersao = new javax.swing.JLabel();
        labelPadrinho = new javax.swing.JLabel();
        labelMadrinha = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabMedium = new javax.swing.JTable();
        txtPadrinho = new javax.swing.JTextField();
        txtMadrinha = new javax.swing.JTextField();
        txtPesquisar = new javax.swing.JTextField();
        labelBatismo = new javax.swing.JLabel();
        txtBatismo = new javax.swing.JTextField();
        labelCoroacao = new javax.swing.JLabel();
        txtCoroacao = new javax.swing.JTextField();
        labelConfirmacao = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelNomeMedium = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelDataEntrada = new javax.swing.JLabel();
        label3Anos = new javax.swing.JLabel();
        label7Anos = new javax.swing.JLabel();
        label14Anos = new javax.swing.JLabel();
        label21Anos = new javax.swing.JLabel();
        label1Ano = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt1Ano = new javax.swing.JTextField();
        txt3Anos = new javax.swing.JTextField();
        txt7Anos = new javax.swing.JTextField();
        txt21Anos = new javax.swing.JTextField();
        txt14Anos = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        radioPadrinho = new javax.swing.JRadioButton();
        radioMadrinha = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelTop.setBackground(new java.awt.Color(255, 255, 255));
        panelTop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        labelTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelTitulo.setText("COROAÇÃO");

        btCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btCancelar.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/cancelar.png"))); // NOI18N
        btCancelar.setText("Sair");
        btCancelar.setToolTipText("Cancelar");
        btCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelar.setMaximumSize(new java.awt.Dimension(51, 43));
        btCancelar.setMinimumSize(new java.awt.Dimension(51, 43));
        btCancelar.setPreferredSize(new java.awt.Dimension(51, 43));
        btCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        txtCodUser.setEditable(false);
        txtCodUser.setText("codUser");

        txtCodMedium.setEditable(false);
        txtCodMedium.setText("codMedium");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/BtCoroa.png"))); // NOI18N

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(labelTitulo)
                .addGap(178, 178, 178)
                .addComponent(txtCodMedium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCodUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCodMedium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelDown.setBackground(new java.awt.Color(255, 255, 255));
        panelDown.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        labelVersao.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        labelVersao.setText("SISTEJM - Versão 1.0 - Interna");

        javax.swing.GroupLayout panelDownLayout = new javax.swing.GroupLayout(panelDown);
        panelDown.setLayout(panelDownLayout);
        panelDownLayout.setHorizontalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDownLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVersao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDownLayout.setVerticalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelVersao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        labelPadrinho.setText("Padrinho:");

        labelMadrinha.setText("Madrinha:");

        tabMedium.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Médium"
            }
        ));
        tabMedium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMediumMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabMedium);

        txtPadrinho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPadrinhoKeyPressed(evt);
            }
        });

        txtMadrinha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMadrinhaKeyPressed(evt);
            }
        });

        txtPesquisar.setToolTipText("Pesquisar");
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        labelBatismo.setText("Batismo:");

        txtBatismo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBatismoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBatismoKeyReleased(evt);
            }
        });

        labelCoroacao.setText("Corôa:");

        txtCoroacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCoroacaoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCoroacaoKeyReleased(evt);
            }
        });

        labelConfirmacao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelConfirmacao.setText("CONFIRMAÇÕES");

        labelNome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelNome.setText("NOME:");

        labelNomeMedium.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelNomeMedium.setText("Aguardando...");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATA DE ENTRADA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 153)));

        labelDataEntrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDataEntrada.setText("Aguardando...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDataEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        label3Anos.setText("3 Anos:");

        label7Anos.setText("7 Anos:");

        label14Anos.setText("14 Anos:");

        label21Anos.setText("21 Anos:");

        label1Ano.setText("1 Ano:");

        txt1Ano.setEditable(false);

        txt3Anos.setEditable(false);

        txt7Anos.setEditable(false);

        txt21Anos.setEditable(false);

        txt14Anos.setEditable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "   SELECIONE   ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 10), new java.awt.Color(0, 0, 204))); // NOI18N

        buttonGroup.add(radioPadrinho);
        radioPadrinho.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        radioPadrinho.setForeground(new java.awt.Color(0, 0, 255));
        radioPadrinho.setText(" PADRINHO");
        radioPadrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPadrinhoActionPerformed(evt);
            }
        });

        buttonGroup.add(radioMadrinha);
        radioMadrinha.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        radioMadrinha.setForeground(new java.awt.Color(204, 0, 204));
        radioMadrinha.setText(" MADRINHA");
        radioMadrinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMadrinhaActionPerformed(evt);
            }
        });

        buttonGroup.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setText(" TODOS");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioPadrinho)
                .addGap(18, 18, 18)
                .addComponent(radioMadrinha)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(radioPadrinho)
                .addComponent(radioMadrinha)
                .addComponent(jRadioButton1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label7Anos)
                                .addGap(18, 18, 18)
                                .addComponent(txt7Anos))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label3Anos)
                                    .addComponent(label1Ano))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txt1Ano, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txt3Anos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label21Anos)
                            .addComponent(label14Anos))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt14Anos, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txt21Anos))
                        .addGap(273, 273, 273))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelMadrinha)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMadrinha))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelPadrinho)
                                    .addGap(20, 20, 20)
                                    .addComponent(txtPadrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(labelCoroacao)
                                        .addGap(33, 33, 33))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelBatismo)
                                        .addGap(25, 25, 25)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBatismo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCoroacao, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelConfirmacao)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNome)
                                .addGap(32, 32, 32)
                                .addComponent(labelNomeMedium)))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNomeMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(labelPadrinho))
                            .addComponent(txtPadrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMadrinha)
                            .addComponent(txtMadrinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelBatismo)
                            .addComponent(txtBatismo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCoroacao)
                            .addComponent(txtCoroacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelConfirmacao)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label1Ano)
                            .addComponent(txt1Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label7Anos)
                                .addComponent(txt7Anos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label3Anos)
                                    .addComponent(txt3Anos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label14Anos)
                                    .addComponent(txt14Anos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label21Anos)
                                    .addComponent(txt21Anos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(panelDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        fechar();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased

        m = new Mediuns();
        m.setAtivo(9);
        m.buscaTabNomeMedium(tabMedium, txtPesquisar.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void tabMediumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMediumMouseClicked

        bat = new Batismo();
        String nome = String.valueOf(tabMedium.getValueAt(tabMedium.getSelectedRow(), 0));        

        switch(this.selectPadr){
            case "m":
                txtPadrinho.setText(nome);
                break;
            case "f":
                txtMadrinha.setText(nome);
                break;
        }
//        if(txtBatismo.getText().equals("")){
//            JOptionPane.showMessageDialog(null, "A data do batismo não pode ficar vazio");
//        }else{
            bat.setCodMedium(Integer.valueOf(txtCodMedium.getText()));
            bat.setMadrinha(txtMadrinha.getText());
            if(txtBatismo.getText().equals("")){
                bat.setDataBatismo("01/01/1901");
            }else{
                bat.setDataBatismo(txtBatismo.getText());
            }
            bat.setPadrinho(txtPadrinho.getText());
            bat.incluiPadrinhosBatismoMedium();
            consultaMedium();
            txtBatismo.requestFocus();
//        }

        // TODO add your handling code here:
    }//GEN-LAST:event_tabMediumMouseClicked

    private void txtCoroacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCoroacaoKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.dia = Integer.valueOf(txtCoroacao.getText().substring(1, 2));
            this.mes = Integer.valueOf(txtCoroacao.getText().substring(3, 5));
            this.ano = Integer.valueOf(txtCoroacao.getText().substring(6, 10));
            completaAnos();
            consultaMedium();
        }
        
    }//GEN-LAST:event_txtCoroacaoKeyPressed

    private void txtCoroacaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCoroacaoKeyReleased

        coroa = new Coroa();
        
        if(txtCoroacao.getText().length() == 2){
            txtCoroacao.setText(txtCoroacao.getText() + "/");
        }
        if(txtCoroacao.getText().length() == 5){//estou no mes
            txtCoroacao.setText(txtCoroacao.getText() + "/");
        }
//        if(txtCoroacao.getText().length() >= 10){//estou no ano
////            completaAnos();
//        }
        
        
    }//GEN-LAST:event_txtCoroacaoKeyReleased

    private void txtBatismoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBatismoKeyReleased
        coroa = new Coroa();
        bat = new Batismo();
        
        if(txtBatismo.getText().length() == 2){
            txtBatismo.setText(txtBatismo.getText() + "/");
        }
        if(txtBatismo.getText().length() == 5){//estou no mes
            txtBatismo.setText(txtBatismo.getText() + "/");
        }
        if(txtBatismo.getText().length() == 10){//estou no ano
            this.mes = Integer.valueOf(txtBatismo.getText().substring(3, 5));
            this.ano = Integer.valueOf(txtBatismo.getText().substring(6, 10));
            
            coroa.setAno(this.ano);
            coroa.setMes(this.mes);
            coroa.setConfirma("s");
            coroa.setDataRealizacao(txtBatismo.getText());
            coroa.setCodtipocoroa(1);
            coroa.setCodmedium(Integer.valueOf(txtCodMedium.getText()));
            coroa.marcaCoroa();
            
            
            // altera batismo
            bat.setCodMedium(Integer.valueOf(txtCodMedium.getText()));
            bat.setDataBatismo(txtBatismo.getText());
            bat.setPadrinho(txtPadrinho.getText());
            bat.setMadrinha(txtMadrinha.getText());
            bat.alterarBatismoMedium();
            
            consultaMedium();
  
        }
        
    }//GEN-LAST:event_txtBatismoKeyReleased

    private void txtBatismoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBatismoKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtCoroacao.setText("");
            txtCoroacao.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBatismoKeyPressed

    private void radioPadrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPadrinhoActionPerformed

        this.selectPadr = "m";
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPadrinhoActionPerformed

    private void radioMadrinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMadrinhaActionPerformed
        this.selectPadr = "f";
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMadrinhaActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        this.selectPadr = "a";
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void txtPadrinhoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPadrinhoKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            bat = new Batismo();
            bat.setPadrinho(txtPadrinho.getText());
            bat.incluiPadrinho();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtPadrinhoKeyPressed

    private void txtMadrinhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMadrinhaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            bat = new Batismo();
            bat.setMadrinha(txtMadrinha.getText());
            bat.incluiMadrinha();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMadrinhaKeyPressed

   
    public void completaAnos(){
        coroa = new Coroa();

        int valor1Ano = this.ano + 1;
        int valor3Anos = this.ano + 3;
        int valor7Anos = this.ano + 7;
        int valor14Anos = this.ano + 14;
        int valor21Anos = this.ano + 21;
        
        coroa.setMes(this.mes);
        coroa.setCodmedium(Integer.valueOf(txtCodMedium.getText()));
//        String mesLongo = retornaMesLongo(this.mes);
        
        coroa.setCodtipocoroa(2);
        coroa.setAno(this.ano);
        coroa.setConfirma("s");
        coroa.setDataRealizacao(txtCoroacao.getText());
        coroa.marcaCoroa();
        
        txt1Ano.setText(String.valueOf(this.mes + " - " + valor1Ano + " | A confirmar"));
        coroa.setCodtipocoroa(3);
        coroa.setConfirma("n");
        coroa.setAno(valor1Ano);
        coroa.setDataRealizacao("01/" + this.mes + "/" + valor1Ano);
        coroa.desmarcaCoroa();
        
        txt3Anos.setText(String.valueOf(this.mes + " - " + valor3Anos + " | A confirmar"));
        coroa.setConfirma("n");
        coroa.setCodtipocoroa(4);
        coroa.setAno(valor3Anos);
        coroa.setDataRealizacao("01/" + this.mes + "/" + valor3Anos);
        coroa.desmarcaCoroa();

        txt7Anos.setText(String.valueOf(this.mes + " - " + valor7Anos + " | A confirmar"));
        coroa.setConfirma("n");
        coroa.setCodtipocoroa(5);
        coroa.setAno(valor7Anos);
        coroa.setDataRealizacao("01/" + this.mes + "/" + valor7Anos);
        coroa.desmarcaCoroa();

        txt14Anos.setText(String.valueOf(this.mes + " - " + valor14Anos + " | A confirmar"));
        coroa.setConfirma("n");
        coroa.setCodtipocoroa(6);
        coroa.setAno(valor14Anos);
        coroa.setDataRealizacao("01/" + this.mes + "/" + valor14Anos);
        coroa.desmarcaCoroa();

        txt21Anos.setText(String.valueOf(this.mes + " - " + valor21Anos + " | A confirmar"));
        coroa.setConfirma("n");
        coroa.setCodtipocoroa(7);
        coroa.setAno(valor21Anos);
        coroa.setDataRealizacao("01/" + this.mes + "/" + valor21Anos);
        coroa.desmarcaCoroa();

        consultaMedium();
   
    }
    
    public String retornaMesLongo(int mes){
        String mesLongo =  null;
        
        if(mes == 1){
            mesLongo = "Janeiro";
        }
        if(mes == 2){
            mesLongo = "Fevereiro";
        }
        if(mes == 3){
            mesLongo = "Março";
        }
        if(mes == 4){
            mesLongo = "Abril";
        }
        if(mes == 5){
            mesLongo = "Maio";
        }
        if(mes == 6){
            mesLongo = "Junho";
        }
        if(mes == 7){
            mesLongo = "Julho";
        }
        if(mes == 8){
            mesLongo = "Agosto";
        }
        if(mes == 9){
            mesLongo = "Setembro";
        }
        if(mes == 10){
            mesLongo = "Outubro";
        }
        if(mes == 11){
            mesLongo = "Novembro";
        }
        if(mes == 12){
            mesLongo = "Dezembro";
        }
        
        return mesLongo;
    }
    
    public void passaCampo(JTextField campo){
        campo.requestFocus();
    }
    
    public void recebeInfo(int idMedium, int codUsuario, String medium, String dataEntrada){

        coroa = new Coroa();
        bat = new Batismo();
        
        String nomeMaiusc = medium;
        txtCodMedium.setText(String.valueOf(idMedium));
        txtCodUser.setText(String.valueOf(codUsuario));
        labelNomeMedium.setText(nomeMaiusc.toUpperCase());
        labelDataEntrada.setText(dataEntrada);
        
        //alimenta coroa
        coroa.setCodmedium(idMedium);
        coroa.verificaCamposPadrao();
        
        if(!coroa.confereBatismoCoroa()){
            coroa.setAno(0);
            coroa.setMes(0);
            coroa.setConfirma("n");
            coroa.setDataRealizacao("01/01/1901");
            coroa.setCodmedium(idMedium);
            coroa.setCodtipocoroa(1);
            coroa.insereCoroa();
        }
        
//        //alimenta batismo
        bat.setCodMedium(idMedium);
        bat.verificaExistente();
        
        tabelaMediuns();
        
        consultaMedium();

    }    
    
    public void fechar(){
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DCoroacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DCoroacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DCoroacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DCoroacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DCoroacao dialog = new DCoroacao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label14Anos;
    private javax.swing.JLabel label1Ano;
    private javax.swing.JLabel label21Anos;
    private javax.swing.JLabel label3Anos;
    private javax.swing.JLabel label7Anos;
    private javax.swing.JLabel labelBatismo;
    private javax.swing.JLabel labelConfirmacao;
    private javax.swing.JLabel labelCoroacao;
    private javax.swing.JLabel labelDataEntrada;
    private javax.swing.JLabel labelMadrinha;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNomeMedium;
    private javax.swing.JLabel labelPadrinho;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelVersao;
    private javax.swing.JPanel panelDown;
    private javax.swing.JPanel panelTop;
    private javax.swing.JRadioButton radioMadrinha;
    private javax.swing.JRadioButton radioPadrinho;
    private javax.swing.JTable tabMedium;
    private javax.swing.JTextField txt14Anos;
    private javax.swing.JTextField txt1Ano;
    private javax.swing.JTextField txt21Anos;
    private javax.swing.JTextField txt3Anos;
    private javax.swing.JTextField txt7Anos;
    private javax.swing.JTextField txtBatismo;
    private javax.swing.JTextField txtCodMedium;
    private javax.swing.JTextField txtCodUser;
    private javax.swing.JTextField txtCoroacao;
    private javax.swing.JTextField txtMadrinha;
    private javax.swing.JTextField txtPadrinho;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
