/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistejm.telas;

import br.com.sistejm.classes.Configuracoes;
import br.com.sistejm.classes.Eventos;
import br.com.sistejm.classes.Produtos;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Michel
 */
public class DEventos extends javax.swing.JDialog {

    Eventos evento;
    Produtos produto;
    Configuracoes config;
    private int coduser;
    private String nomeEvento;
    private int idEvento;
    private String nomeUsuario;
    private String transacao;

    public String getTransacao() {
        return transacao;
    }

    public void setTransacao(String transacao) {
        this.transacao = transacao;
    }

    public String getNomeUsuario() {
        return nomeUsuario;
    }

    public void setNomeUsuario(String nomeUsuario) {
        this.nomeUsuario = nomeUsuario;
    }

    public String getNomeEvento() {
        return nomeEvento;
    }

    public void setNomeEvento(String nomeEvento) {
        this.nomeEvento = nomeEvento;
    }

    public int getCoduser() {
        return coduser;
    }

    public void setCoduser(int coduser) {
        this.coduser = coduser;
    }

    public int getIdEvento() {
        return idEvento;
    }

    public void setIdEvento(int idEvento) {
        this.idEvento = idEvento;
    }
    
    
    /**
     * Creates new form DEventos
     */
    public DEventos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ativaTexto(false);
        ativaBotoes(true);
    }
    
    public void recebeCodUser(int codigo, String u){
        this.coduser = codigo;
        this.nomeUsuario = u;
        txtCodeUser.setText(String.valueOf(this.coduser));
        
    }
    
    public void ativaTexto(boolean valor){
        txtCodeUser.setVisible(valor);
        txtIdEvento.setVisible(valor);        
        txtNomeEvento.setVisible(valor);        
    }
    
    public void ativaBotoes(boolean valor){
        btSair.setVisible(valor);
        btExcluir.setVisible(valor);        
        btSalvar.setVisible(valor);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTop = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        txtCodeUser = new javax.swing.JTextField();
        txtIdEvento = new javax.swing.JTextField();
        txtNomeEvento = new javax.swing.JTextField();
        btSair = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        labelNome = new javax.swing.JLabel();
        txtEvento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoTexto = new javax.swing.JTextArea();
        panelDown = new javax.swing.JPanel();
        labelVersao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        panelTop.setBackground(new java.awt.Color(255, 255, 255));
        panelTop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        labelTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelTitulo.setText("Eventos");

        txtCodeUser.setEditable(false);

        txtIdEvento.setEditable(false);

        txtNomeEvento.setEditable(false);

        btSair.setBackground(new java.awt.Color(255, 255, 255));
        btSair.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/cancelar.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.setToolTipText("Sair");
        btSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btSalvar.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/fileSave.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setToolTipText("Salvar");
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btExcluir.setBackground(new java.awt.Color(255, 255, 255));
        btExcluir.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/botaoexcluir.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setToolTipText("Excluir");
        btExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTopLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(txtNomeEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTopLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelTitulo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtIdEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCodeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtIdEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNomeEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        labelNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelNome.setText("Evento:");

        txtEvento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtEvento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEventoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEventoKeyReleased(evt);
            }
        });

        table.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        campoTexto.setEditable(false);
        campoTexto.setColumns(20);
        campoTexto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        campoTexto.setForeground(new java.awt.Color(0, 0, 255));
        campoTexto.setRows(5);
        jScrollPane2.setViewportView(campoTexto);

        panelDown.setBackground(new java.awt.Color(255, 255, 255));
        panelDown.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        labelVersao.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        labelVersao.setText("SISTEJM - Versão 1.0 - Interna");

        javax.swing.GroupLayout panelDownLayout = new javax.swing.GroupLayout(panelDown);
        panelDown.setLayout(panelDownLayout);
        panelDownLayout.setHorizontalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDownLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDownLayout.setVerticalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelVersao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNome)
                        .addGap(18, 18, 18)
                        .addComponent(txtEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(panelDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(txtEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEventoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEventoKeyPressed

        sairTecla(evt);
        evento = new Eventos();
        produto = new Produtos();
        config = new Configuracoes();
        
        switch(this.transacao){
            case "eventos":
                if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                    if(!table.toString().isEmpty()){
                        this.nomeEvento = txtEvento.getText();
                        evento.setEvento(this.nomeEvento);
                        evento.setCodUsuario(coduser);
                        if(evento.incluirEvento()){
                            preencheCampo("\nEvento incluso com sucesso !");
                            txtEvento.setText("");
                            txtEvento.requestFocus();
                            evento.preencheTabelaEvento(table);
                            //System.out.println(this.nomeUsuario + " - " + this.nomeEvento);
                            config.gravaAtividades("Criação de Evento", this.nomeUsuario, this.nomeEvento);
                        }
                    }else{
                        System.out.println("Está vazio.");
                    }
                }else if(evt.getKeyCode() == KeyEvent.VK_F3){
                    evento.pesquisaCampoTabela(table, txtEvento);            
                }
            break;
            
            case "produtos":
                if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                    if(!table.toString().isEmpty()){
                        this.nomeEvento = txtEvento.getText();
                        produto.setProduto(txtEvento.getText());
                        produto.setCodUsuario(coduser);
                        if(produto.verificaDuplicidade()){
                            preencheCampo("\nProduto salvo com sucesso !");
                            txtEvento.setText("");
                            txtEvento.requestFocus();
                            produto.preencheTabelaProdutos(table);
                            config.gravaAtividades("Criação de Produtos", this.nomeUsuario, this.nomeEvento);
                        }else{
                            preencheCampo("\nProduto salvo com sucesso ! (Alteração)");
                            txtEvento.setText("");
                            txtEvento.requestFocus();
                            produto.preencheTabelaProdutos(table);
                            config.gravaAtividades("Alteração de Produtos", this.nomeUsuario, this.nomeEvento);
                        }
                    }else{
                        System.out.println("Está vazio.");
                    }
                }else if(evt.getKeyCode() == KeyEvent.VK_F3){
                    evento.pesquisaCampoTabela(table, txtEvento);            
                }                
            break;

        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEventoKeyPressed

    private void tableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyPressed
        ativaBotoes(true);
        txtEvento.setText(table.getSelectionModel().toString());
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tableKeyPressed

    private void txtEventoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEventoKeyReleased
        evento = new Eventos();
        produto = new Produtos();
        
        switch(this.transacao){
            case "eventos":
                if(txtEvento.getText().length() > 0){
                    evento.pesquisaCampoTabela(table, txtEvento);
                }else if(txtEvento.getText().length() == 0){
                    evento.preencheTabelaEvento(table);
                }
                break;
            case "produtos":
                if(txtEvento.getText().length() > 0){
                    produto.pesquisaCampoTabela(table, txtEvento);
                }else if(txtEvento.getText().length() == 0){
                    produto.preencheTabelaProdutos(table);
                }
                break;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEventoKeyReleased

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        ativaBotoes(true);
        String selecao = String.valueOf(table.getValueAt(table.getSelectedRow(), 1));
        String selecaoId = String.valueOf(table.getValueAt(table.getSelectedRow(), 0));
        txtEvento.setText(selecao);
        txtIdEvento.setText(selecaoId);
//        txtEvento.setText(table.getValueAt(1, 1).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        //geraTudoNovo(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed

        this.fechar();
        // TODO add your handling code here:
    }//GEN-LAST:event_btSairActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

        evento = new Eventos();
        produto = new Produtos();
        config = new Configuracoes();
        
        switch(this.transacao){
            case "eventos":

                if(!txtIdEvento.getText().equals("")){
                    evento.setIdEventos(Integer.parseInt(txtIdEvento.getText()));
                }
                evento.setCodUsuario(coduser);
                evento.setEvento(txtEvento.getText());
                if(evento.verificaDuplicidade()){
                    preencheCampo("Salvo com sucesso !");
                    evento.preencheTabelaEvento(table);
                    limpaCampos();
                }             
            break;
            
            case "produtos":
                if(!txtIdEvento.getText().equals("")){
                    produto.setIdProduto(Integer.parseInt(txtIdEvento.getText()));
                }
                produto.setCodUsuario(coduser);
                produto.setProduto(txtEvento.getText());
                if(produto.verificaDuplicidade()){
                    preencheCampo("Salvo com sucesso !");
                    produto.preencheTabelaProdutos(table);
                    limpaCampos();
                }             

            break;

        }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        evento = new Eventos();
        produto = new Produtos();
        
        String inform = null;
            if(this.transacao.equals("eventos")){
                inform = "evento";
                
            }else{
                inform = "produto";
            }        
        if(!txtIdEvento.getText().equals("")){
            if(JOptionPane.showConfirmDialog(null, "Deseja excluir o " + inform + " selecionado?", "Exclusão", JOptionPane.YES_NO_OPTION) == 0){
                if(inform.equals("evento")){
                    evento.setIdEventos(Integer.parseInt(txtIdEvento.getText()));
                    if(evento.excluirEvento()){
                        preencheCampo("Evento excluído com sucesso !");
                        evento.preencheTabelaEvento(table);
                        limpaCampos();
                    }
                }else{
                    produto.setIdProduto(Integer.parseInt(txtIdEvento.getText()));
                    if(produto.excluirProduto()){
                        preencheCampo("Produto excluído com sucesso !");
                        produto.preencheTabelaProdutos(table);
                        limpaCampos();
                    }
                }
            }
        }else{
                preencheCampo("Selecione o " + inform +" para exclusão.");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btExcluirActionPerformed


    public void sairTecla(KeyEvent ev){
        if(ev.getKeyCode() == KeyEvent.VK_ESCAPE){
            fechar();
        }
    }
    
    public void limpaCampos(){
        txtEvento.setText("");
        txtEvento.requestFocus();
    }
    
    public void identificaOperacao(String operacao){
        this.transacao = operacao;

        switch(operacao){
            case "evento":
                this.transacao = "eventos";
                evento = new Eventos();
                labelTitulo.setText("Evento");
                this.setTitle("Evento");
                labelNome.setText("Evento:");
                boasVindasEventos();
                evento.preencheTabelaEvento(table);
                break;
            case "produto":
                produto = new Produtos();
                this.transacao = "produtos";
                labelTitulo.setText("Produtos");
                labelNome.setText("Produto:");
                boasVindasProdutos();
                produto.preencheTabelaProdutos(table);
                break;
        }
    }
    
    public void fechar(){
        this.dispose();
    }
    
    public void boasVindasEventos(){
        preencheCampo("Bem-vindo ao Evento.");
        preencheCampo("\nAqui será registrado os eventos da casa, como festas, excursões etc.");
        preencheCampo("\nTodos os registros serão usados para os demais registros, para facilitar a busca e relatórios.");
        preencheCampo("\nAo digitar, aparecerá na tabela abaixo, caso exista. Se existe, digite <ESC>, se não digite o evento e <ENTER>.");
    }
    
    public void boasVindasProdutos(){
        preencheCampo("Bem-vindo ao Produtos.");
        preencheCampo("\nAqui será registrado os produtos necessários para a casa.");
        preencheCampo("\nVisando facilitar a busca e relatórios, assim como registrar a colaboração de médiuns.");
        preencheCampo("\nAo digitar, aparecerá na tabela abaixo, caso exista. Se existe, digite <ESC>, se não digite o evento e <ENTER>.");
    }
    
    public void preencheCampo(String texto){
        campoTexto.setLineWrap(true);
        campoTexto.append("\n" + texto);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DEventos dialog = new DEventos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSalvar;
    private javax.swing.JTextArea campoTexto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelVersao;
    private javax.swing.JPanel panelDown;
    private javax.swing.JPanel panelTop;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtCodeUser;
    private javax.swing.JTextField txtEvento;
    private javax.swing.JTextField txtIdEvento;
    private javax.swing.JTextField txtNomeEvento;
    // End of variables declaration//GEN-END:variables
}
