/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistejm.telas;

import br.com.sistejm.classes.Configuracoes;
import br.com.sistejm.classes.Usuario;
import java.awt.event.KeyEvent;

/**
 *
 * @author Michel
 */
public class DFLogin extends javax.swing.JFrame {

    private int iduser;
    private String user;
    
    Usuario usuario;
    Configuracoes config;
    TelaInicial tela;

    public int getIduser() {
        return iduser;
    }

    public void setIduser(int iduser) {
        this.iduser = iduser;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    
    /**
     * Creates new form DFLogin
     */
    public DFLogin() {
        initComponents();
        campoAdm();
        botaoTela();
    }

    public void campoAdm(){
        txtUsuario.setText("michel");
        txtSenha.setText("m1ch3l4p");
        txtSenha.requestFocus();
    }
    
    public void botaoTela(){
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    }

    public void sairTelaLogin(KeyEvent ev){
        tela = new TelaInicial();
        if(ev.getKeyCode() == KeyEvent.VK_ESCAPE){
            fechar();
   
        }
    }
    
    public void limpaPanelLogin(){
        txtSenha.setText("");
    }
    
    public void fechar(){
        this.setAutoRequestFocus(false);
        this.dispose();
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        labelSenha = new javax.swing.JLabel();
        btAcessar = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        labelMensagem = new javax.swing.JLabel();
        btCancelar = new javax.swing.JButton();
        labelmsgerror = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        labelUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelUsuario.setText("Usuário:");

        txtUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUsuario.setMinimumSize(new java.awt.Dimension(6, 25));
        txtUsuario.setPreferredSize(new java.awt.Dimension(6, 25));
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });

        txtSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSenha.setMinimumSize(new java.awt.Dimension(6, 25));
        txtSenha.setPreferredSize(new java.awt.Dimension(6, 25));
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
        });

        labelSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelSenha.setText("Senha:");

        btAcessar.setBackground(new java.awt.Color(255, 255, 255));
        btAcessar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/Oks16x16.png"))); // NOI18N
        btAcessar.setText("Acessar");
        btAcessar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAcessar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcessarActionPerformed(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("BEM-VINDO AO SISTEJM");

        labelMensagem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMensagem.setText("Preencha seus dados para continuar");

        btCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/cancelar.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        labelmsgerror.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelmsgerror.setForeground(new java.awt.Color(153, 0, 0));
        labelmsgerror.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelmsgerror.setText("Mensagens de erro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelmsgerror, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelUsuario)
                                    .addComponent(labelSenha))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(btAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelMensagem)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAcessar)
                    .addComponent(btCancelar))
                .addGap(20, 20, 20)
                .addComponent(labelmsgerror)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        sairTelaLogin(evt);
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(txtUsuario.getText().length() > 0){
                txtSenha.setText("");
                txtSenha.requestFocus();
                //            }else{
                //                preencheCampo("\nO campo não pode ficar vazio.");
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        sairTelaLogin(evt);
        tela = new TelaInicial();
        usuario = new Usuario();
        config = new Configuracoes();

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(txtSenha.getText().length() > 0){
                
                entrar();
//                logar();

//                usuario.setNome(txtUsuario.getText());
//                usuario.setSenha(txtSenha.getText());
//
//                this.setIduser(usuario.consultaLoginUsuario());
//                if(this.iduser > 0){
//                    tela.autorizaUsuario(this.iduser);
//                    limpaPanelLogin();
//                    tela.desativaInoperantes();
//                    fechar();

                }else{
                    labelmsgerror.setText("Usuário inexistente");
                }
            }
//        }
    }//GEN-LAST:event_txtSenhaKeyPressed

    private void btAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcessarActionPerformed
        entrar();
//        logar();
    }//GEN-LAST:event_btAcessarActionPerformed

    public void entrar(){
        usuario = new Usuario();
        config = new Configuracoes();
        tela = new TelaInicial();

        if(txtUsuario.getText().equals("")){
            labelmsgerror.setText("Usuário vazio. Digite o nome do usuário");
        }else{
            if(txtSenha.getText().equals("")){
                labelmsgerror.setText("Senha vazia. Digite sua senha");
            }else{
                usuario.setNome(txtUsuario.getText());
                usuario.setSenha(txtSenha.getText());

                this.setIduser(usuario.consultaLoginUsuario());
                if(this.iduser > 0){
                    limpaPanelLogin();
                    tela.setIduser(usuario.consultaLoginUsuario());
                    tela.recebeDados(this.user, usuario.retornaAcesso(), this.iduser);
//                    tela.autorizaUsuario();

//                    tela.setIduser(usuario.consultaLoginUsuario());
//                    tela.autorizaUsuario();
                    tela.setTitle("SISTEJM - Sistema TEJM");
                    tela.setLocationRelativeTo(tela);
                    tela.setExtendedState(tela.MAXIMIZED_BOTH);
                    tela.setDefaultCloseOperation(tela.EXIT_ON_CLOSE);
                    tela.setVisible(true);
                    fechar();

                }else{
                    labelmsgerror.setText("Usuário inexistente");
                }
            }

        }
        
        
//        this.dispose();
        
    }
    
    public void logar(){
        usuario = new Usuario();
        config = new Configuracoes();
        tela = new TelaInicial();

        if(txtUsuario.getText().equals("")){
            labelmsgerror.setText("Usuário vazio. Digite o nome do usuário");
        }else{
            if(txtSenha.getText().equals("")){
                labelmsgerror.setText("Senha vazia. Digite sua senha");
            }else{
                usuario.setNome(txtUsuario.getText());
                usuario.setSenha(txtSenha.getText());

                this.setIduser(usuario.consultaLoginUsuario());
                this.setUser(usuario.retornaUsuario());
                if(this.iduser > 0){
                    limpaPanelLogin();
                    tela.setIduser(this.iduser);
                    usuario.setIdUsuario(this.iduser);
                    tela.recebeDados(this.user, usuario.retornaAcesso(), this.iduser);
//                    tela.autorizaUsuario();
                    fechar();

                }else{
                    labelmsgerror.setText("Usuário inexistente");
                }
            }

        }
        
    }
    
    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        fechar();
        // TODO add your handling code here:
    }//GEN-LAST:event_btCancelarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

//        tela = new TelaInicial();
//        tela.autorizaUsuario();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        config = new Configuracoes();
        String pathBanco = "C:\\sistejm\\config\\banco.dat";
        String pathUser = "C:\\sistejm\\config\\datauser.dat";
        
        config.extendOriginal(pathBanco);
        config.extendOriginal(pathUser);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DFLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAcessar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelMensagem;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel labelmsgerror;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
