/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistejm.telas;

import br.com.sistejm.classes.Configuracoes;
import br.com.sistejm.classes.Mediuns;
import br.com.sistejm.classes.Mensalidade;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Michel
 */
public class DMensalidadeMediuns extends javax.swing.JDialog {

    
    Mediuns m;
    Mensalidade men;
    Calendar cal;
    Configuracoes config;
    TelaInicial inicial;
    DRelatorioMensalidade relmen;
    
    private String user;

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }
    
    
    
    /**
     * Creates new form DMensalidadeMediuns
     */
    public DMensalidadeMediuns(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        preencheData();
        preenchePreco();
        ocultaText(false);
        preencheTabMediuns();
        tabelaMediuns.setRowSelectionAllowed(true);
    }
    
    public void preencheData(){
        cal = new GregorianCalendar();
        int ano = cal.get(Calendar.YEAR);
        txtAno.setText(String.valueOf(ano));
    }
    
    public void preenchePreco(){
        txtValor.setText("20,00");
    }
    
    public void preencheTabMediuns(){
        m = new Mediuns();
        m.preencheTabNomeMedium(tabelaMediuns);
    }
    
    public void ocultaText(boolean valor){
        txtData.setVisible(valor);
        txtCodMedium.setVisible(valor);
        txtCodUser.setVisible(valor);
    }
    
    public void recebeInfo(int codUsuario){
        txtCodUser.setText(String.valueOf(codUsuario));
    }
    
    public void marcaPagto(JCheckBox mes, int codMes){
        men = new Mensalidade();
        if(!txtCodMedium.getText().equals("")){
            if(mes.isSelected()){
                men.setCodMedium(Integer.valueOf(txtCodMedium.getText()));
                men.setMes(codMes);
                men.setCodUsuario(Integer.valueOf(txtCodUser.getText()));
                men.setAno(Integer.valueOf(txtAno.getText()));
                men.setDataPagamento(txtDataMovimento.getText());
                men.setValor(txtValor.getText());
                men.marcaPagamento();

                men.consultaMesesPagos(cJan, cFev, cMar, cAbr, 
                    cMai, cJun, cJul, cAgo, cSet, cOut, 
                    cNov, cDez);            
                //insere o mes
            }else{
                men.setCodMedium(Integer.valueOf(txtCodMedium.getText()));
                men.setMes(codMes);
                men.setCodUsuario(Integer.valueOf(txtCodUser.getText()));
                men.setAno(Integer.valueOf(txtAno.getText()));
                men.setDataPagamento(txtDataMovimento.getText());
                men.setValor(txtValor.getText());
                men.desmarcaPagamento();
                men.consultaMesesPagos(cJan, cFev, cMar, cAbr, 
                    cMai, cJun, cJul, cAgo, cSet, cOut, 
                    cNov, cDez);   
                //exclui o mes
            }        
        }else{
            JOptionPane.showConfirmDialog(null, "Selecione o médium corretamente, até aparecer o nome no campo", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        }
        
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTop = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        btCancelar = new javax.swing.JButton();
        txtData = new javax.swing.JTextField();
        txtCodUser = new javax.swing.JTextField();
        txtCodMedium = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btImprimir = new javax.swing.JButton();
        panelAno = new javax.swing.JPanel();
        txtAno = new javax.swing.JTextField();
        panelValor = new javax.swing.JPanel();
        txtValor = new javax.swing.JTextField();
        panelDown = new javax.swing.JPanel();
        labelVersao = new javax.swing.JLabel();
        calendario = new com.toedter.calendar.JCalendar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMediuns = new javax.swing.JTable();
        txtPesquisa = new javax.swing.JTextField();
        panelMeses = new javax.swing.JPanel();
        cAgo = new javax.swing.JCheckBox();
        cNov = new javax.swing.JCheckBox();
        cJul = new javax.swing.JCheckBox();
        cMar = new javax.swing.JCheckBox();
        cOut = new javax.swing.JCheckBox();
        cJun = new javax.swing.JCheckBox();
        cFev = new javax.swing.JCheckBox();
        cMai = new javax.swing.JCheckBox();
        cDez = new javax.swing.JCheckBox();
        cAbr = new javax.swing.JCheckBox();
        cJan = new javax.swing.JCheckBox();
        cSet = new javax.swing.JCheckBox();
        labelDataMovimento = new javax.swing.JLabel();
        txtDataMovimento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelTop.setBackground(new java.awt.Color(255, 255, 255));
        panelTop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        labelTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelTitulo.setText("MENSALIDADE DE MÉDIUNS");

        btCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btCancelar.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/cancelar.png"))); // NOI18N
        btCancelar.setText("Sair");
        btCancelar.setToolTipText("Cancelar");
        btCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelar.setMaximumSize(new java.awt.Dimension(51, 43));
        btCancelar.setMinimumSize(new java.awt.Dimension(51, 43));
        btCancelar.setPreferredSize(new java.awt.Dimension(51, 43));
        btCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        txtData.setEditable(false);

        txtCodUser.setEditable(false);
        txtCodUser.setText("codUser");

        txtCodMedium.setEditable(false);
        txtCodMedium.setText("codMedium");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/BtFinaceiro1.png"))); // NOI18N

        btImprimir.setBackground(new java.awt.Color(255, 255, 255));
        btImprimir.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        btImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/icon16x16Relatorio.png"))); // NOI18N
        btImprimir.setText("Relatório");
        btImprimir.setToolTipText("Relatório");
        btImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(labelTitulo)
                .addGap(106, 106, 106)
                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCodMedium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCodUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelTopLayout.createSequentialGroup()
                        .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCodUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCodMedium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelAno.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ANO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 0, 153))); // NOI18N

        txtAno.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtAno.setForeground(new java.awt.Color(0, 0, 153));
        txtAno.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout panelAnoLayout = new javax.swing.GroupLayout(panelAno);
        panelAno.setLayout(panelAnoLayout);
        panelAnoLayout.setHorizontalGroup(
            panelAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAno, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelAnoLayout.setVerticalGroup(
            panelAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        panelValor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " VALOR R$ ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 0, 153))); // NOI18N

        txtValor.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtValor.setForeground(new java.awt.Color(0, 0, 153));
        txtValor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout panelValorLayout = new javax.swing.GroupLayout(panelValor);
        panelValor.setLayout(panelValorLayout);
        panelValorLayout.setHorizontalGroup(
            panelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelValorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtValor, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelValorLayout.setVerticalGroup(
            panelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelValorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        panelDown.setBackground(new java.awt.Color(255, 255, 255));
        panelDown.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        labelVersao.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        labelVersao.setText("SISTEJM - Versão 1.0 - Interna");

        javax.swing.GroupLayout panelDownLayout = new javax.swing.GroupLayout(panelDown);
        panelDown.setLayout(panelDownLayout);
        panelDownLayout.setHorizontalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDownLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVersao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDownLayout.setVerticalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelVersao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        calendario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " DATA DO MOVIMENTO ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        calendario.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                calendarioPropertyChange(evt);
            }
        });

        tabelaMediuns.setForeground(new java.awt.Color(0, 0, 102));
        tabelaMediuns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaMediuns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMediunsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaMediuns);

        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        cAgo.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        cAgo.setForeground(new java.awt.Color(51, 51, 51));
        cAgo.setText("AGOSTO");
        cAgo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cAgo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cAgo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cAgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cAgoActionPerformed(evt);
            }
        });

        cNov.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        cNov.setForeground(new java.awt.Color(51, 51, 51));
        cNov.setText("NOVEMBRO");
        cNov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cNov.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cNov.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cNov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNovActionPerformed(evt);
            }
        });

        cJul.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        cJul.setForeground(new java.awt.Color(51, 51, 51));
        cJul.setText("JULHO");
        cJul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cJul.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cJul.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cJul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cJulActionPerformed(evt);
            }
        });

        cMar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        cMar.setForeground(new java.awt.Color(51, 51, 51));
        cMar.setText("MARÇO");
        cMar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cMar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cMar.setPreferredSize(new java.awt.Dimension(71, 41));
        cMar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cMar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cMarActionPerformed(evt);
            }
        });

        cOut.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        cOut.setForeground(new java.awt.Color(51, 51, 51));
        cOut.setText("OUTUBRO");
        cOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cOut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cOutActionPerformed(evt);
            }
        });

        cJun.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        cJun.setForeground(new java.awt.Color(51, 51, 51));
        cJun.setText("JUNHO");
        cJun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cJun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cJun.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cJun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cJunActionPerformed(evt);
            }
        });

        cFev.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        cFev.setForeground(new java.awt.Color(51, 51, 51));
        cFev.setText("FEVEREIRO");
        cFev.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cFev.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cFev.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cFev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cFevActionPerformed(evt);
            }
        });

        cMai.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        cMai.setForeground(new java.awt.Color(51, 51, 51));
        cMai.setText("MAIO");
        cMai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cMai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cMai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cMaiActionPerformed(evt);
            }
        });

        cDez.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        cDez.setForeground(new java.awt.Color(51, 51, 51));
        cDez.setText("DEZEMBRO");
        cDez.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cDez.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cDez.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cDez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDezActionPerformed(evt);
            }
        });

        cAbr.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        cAbr.setForeground(new java.awt.Color(51, 51, 51));
        cAbr.setText("ABRIL");
        cAbr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cAbr.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cAbr.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cAbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cAbrActionPerformed(evt);
            }
        });

        cJan.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        cJan.setForeground(new java.awt.Color(51, 51, 51));
        cJan.setText("JANEIRO");
        cJan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cJan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cJan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cJan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cJanActionPerformed(evt);
            }
        });

        cSet.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        cSet.setForeground(new java.awt.Color(51, 51, 51));
        cSet.setText("SETEMBRO");
        cSet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cSet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cSet.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMesesLayout = new javax.swing.GroupLayout(panelMeses);
        panelMeses.setLayout(panelMesesLayout);
        panelMesesLayout.setHorizontalGroup(
            panelMesesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMesesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelMesesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelMesesLayout.createSequentialGroup()
                        .addGroup(panelMesesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cJan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cFev, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelMesesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cJun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cMai, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelMesesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelMesesLayout.createSequentialGroup()
                            .addComponent(cAbr, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cAgo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMesesLayout.createSequentialGroup()
                            .addComponent(cMar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cJul, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMesesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cNov, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cSet, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cOut, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cDez, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        panelMesesLayout.setVerticalGroup(
            panelMesesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMesesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMesesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelMesesLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(cJul))
                    .addGroup(panelMesesLayout.createSequentialGroup()
                        .addGroup(panelMesesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cJan)
                            .addComponent(cMai)
                            .addComponent(cOut))
                        .addGap(18, 18, 18)
                        .addGroup(panelMesesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cSet)
                            .addComponent(cJun)
                            .addComponent(cFev))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelMesesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cMar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cNov, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(panelMesesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cAbr)
                    .addComponent(cAgo)
                    .addComponent(cDez))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelDataMovimento.setText("Data de movimento:");

        txtDataMovimento.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPesquisa)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(panelMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelDataMovimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDataMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(calendario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDataMovimento)
                            .addComponent(txtDataMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 27, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        fechar();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void cSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSetActionPerformed
        marcaPagto(cSet, 9);
        // TODO add your handling code here:
    }//GEN-LAST:event_cSetActionPerformed

    private void cJanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cJanActionPerformed

        marcaPagto(cJan, 1);
        // TODO add your handling code here:
    }//GEN-LAST:event_cJanActionPerformed

    private void cMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cMaiActionPerformed
        marcaPagto(cMai, 5);
        // TODO add your handling code here:
    }//GEN-LAST:event_cMaiActionPerformed

    private void cDezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDezActionPerformed
        marcaPagto(cDez, 12);
        // TODO add your handling code here:
    }//GEN-LAST:event_cDezActionPerformed

    private void cJunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cJunActionPerformed
        marcaPagto(cJun, 6);
        // TODO add your handling code here:
    }//GEN-LAST:event_cJunActionPerformed

    private void cFevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cFevActionPerformed
        marcaPagto(cFev, 2);
        // TODO add your handling code here:
    }//GEN-LAST:event_cFevActionPerformed

    private void cMarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cMarActionPerformed
        marcaPagto(cMar, 3);
        // TODO add your handling code here:
    }//GEN-LAST:event_cMarActionPerformed

    private void cOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cOutActionPerformed
        marcaPagto(cOut, 10);
        // TODO add your handling code here:
    }//GEN-LAST:event_cOutActionPerformed

    private void cNovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNovActionPerformed
        marcaPagto(cNov, 11);
        // TODO add your handling code here:
    }//GEN-LAST:event_cNovActionPerformed

    private void cJulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cJulActionPerformed
        marcaPagto(cJul, 7);
        // TODO add your handling code here:
    }//GEN-LAST:event_cJulActionPerformed

    private void cAgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cAgoActionPerformed
        marcaPagto(cAgo, 8);
        // TODO add your handling code here:
    }//GEN-LAST:event_cAgoActionPerformed

    private void cAbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cAbrActionPerformed
        marcaPagto(cAbr, 4);
        // TODO add your handling code here:
    }//GEN-LAST:event_cAbrActionPerformed

    private void calendarioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_calendarioPropertyChange
        java.util.Date g = calendario.getDate();
        SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
//        SimpleDateFormat fsql = new SimpleDateFormat("yyyy-MM-dd"); 
        txtData.setText(f.format(g));
        txtDataMovimento.setText(f.format(g));

//        String mesSelect = txtDataSaida.getText().substring(3, 5);
        String anoSelect = txtDataMovimento.getText().substring(6, 10);
        txtAno.setText(anoSelect);
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarioPropertyChange

    private void tabelaMediunsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMediunsMouseClicked

        m = new Mediuns();
        String nomeMedium = String.valueOf(tabelaMediuns.getValueAt(tabelaMediuns.getSelectedRow(), 0));
        txtPesquisa.setText(nomeMedium);
        txtCodMedium.setText(String.valueOf(m.retornaIdMedium(nomeMedium)));
        
        men = new Mensalidade();
        men.setCodMedium(Integer.valueOf(txtCodMedium.getText()));
        men.setAno(Integer.valueOf(txtAno.getText()));
        men.consultaMesesPagos(cJan, cFev, cMar, cAbr, 
            cMai, cJun, cJul, cAgo, cSet, cOut, 
            cNov, cDez);   
        
        
    }//GEN-LAST:event_tabelaMediunsMouseClicked

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased

    m = new Mediuns();
    m.buscaTabNomeMedium(tabelaMediuns, txtPesquisa.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed

        config = new Configuracoes();
        fechar();
        inicial = new TelaInicial();
        relmen = new DRelatorioMensalidade(inicial, false);
        config.gravaAtividades("Mensalidade", this.user, "Abertura de relatório de Mensalidade");

//        relmen.recebeInfo(user);
        relmen.setLocationRelativeTo(relmen);
        relmen.setAutoRequestFocus(true);
        relmen.setTitle("RELATÓRIO DE MENSALIDADES");
        relmen.setVisible(true);
        fechar();

        // TODO add your handling code here:
    }//GEN-LAST:event_btImprimirActionPerformed

    public void fechar(){
        this.setAutoRequestFocus(false);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DMensalidadeMediuns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DMensalidadeMediuns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DMensalidadeMediuns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DMensalidadeMediuns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DMensalidadeMediuns dialog = new DMensalidadeMediuns(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btImprimir;
    private javax.swing.JCheckBox cAbr;
    private javax.swing.JCheckBox cAgo;
    private javax.swing.JCheckBox cDez;
    private javax.swing.JCheckBox cFev;
    private javax.swing.JCheckBox cJan;
    private javax.swing.JCheckBox cJul;
    private javax.swing.JCheckBox cJun;
    private javax.swing.JCheckBox cMai;
    private javax.swing.JCheckBox cMar;
    private javax.swing.JCheckBox cNov;
    private javax.swing.JCheckBox cOut;
    private javax.swing.JCheckBox cSet;
    private com.toedter.calendar.JCalendar calendario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDataMovimento;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelVersao;
    private javax.swing.JPanel panelAno;
    private javax.swing.JPanel panelDown;
    private javax.swing.JPanel panelMeses;
    private javax.swing.JPanel panelTop;
    private javax.swing.JPanel panelValor;
    private javax.swing.JTable tabelaMediuns;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtCodMedium;
    private javax.swing.JTextField txtCodUser;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDataMovimento;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
