/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistejm.telas;

import br.com.sistejm.classes.Acesso;
import br.com.sistejm.classes.Usuario;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Michel
 */
public class DNovoUsuario extends javax.swing.JDialog {

    TelaInicial inicial = new TelaInicial();
    DPrimeiroUsuario primeiro = new DPrimeiroUsuario(inicial, false);
    Acesso acesso;
    Calendar cal = new GregorianCalendar();
    Usuario user = new Usuario();
    /**
     * Creates new form DNovoUsuario
     */
    public DNovoUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //preencheComboAcesso();
        boasVindas();
        //verificaUsuario();
    }

    public void preencheComboAcesso(){
        acesso = new Acesso();
        acesso.completaComboAcesso(comboAcesso);
    }
    
    public void sair(){
        this.dispose();
    }
    
    public void boasVindas(){
        preencheComboAcesso();
        limpaCampos();
        preencheTexto("\nBem-vindo ao Sistema TEJM (SISTEJM)");
        preencheTexto("\n===================================");
        preencheTexto("\nPreencha os campos para cadastrar o novo usuário.");
//        preencheTexto("\nAo terminar, pressione <ENTER> para salvar os dados.");      
    }
    
    public void preencheTexto(String texto){
        campoTexto.setLineWrap(true);
        campoTexto.append(texto);
    }
    
    public void limpaCampos(){
        txtUsuario.setText("");
        txtSenha.setText("");
        txtEmail.setText("");

        txtSenha.setEditable(false);
        txtEmail.setEditable(false);
        labelBotao.setText("Aguardando...");
        txtUsuario.requestFocus();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is alway
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSenha = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoTexto = new javax.swing.JTextArea();
        panelTop = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        labelAcesso = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        panelDown = new javax.swing.JPanel();
        labelTitilo2 = new javax.swing.JLabel();
        comboAcesso = new javax.swing.JComboBox<>();
        labelBotao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        labelSenha.setText("Senha:");

        labelNome.setText("Nome Usuário:");

        campoTexto.setEditable(false);
        campoTexto.setColumns(20);
        campoTexto.setRows(5);
        jScrollPane1.setViewportView(campoTexto);

        panelTop.setBackground(new java.awt.Color(255, 255, 255));
        panelTop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        labelTitulo.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        labelTitulo.setText("Novo Usuário");

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        txtEmail.setEditable(false);
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        txtSenha.setEditable(false);
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSenhaKeyReleased(evt);
            }
        });

        labelAcesso.setText("Acesso:");

        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyReleased(evt);
            }
        });

        labelEmail.setText("E-mail:");

        panelDown.setBackground(new java.awt.Color(255, 255, 255));
        panelDown.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        labelTitilo2.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        labelTitilo2.setText("SISTEJM - Versão 1");

        javax.swing.GroupLayout panelDownLayout = new javax.swing.GroupLayout(panelDown);
        panelDown.setLayout(panelDownLayout);
        panelDownLayout.setHorizontalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDownLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitilo2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDownLayout.setVerticalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitilo2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        comboAcesso.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        comboAcesso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboAcessoMouseClicked(evt);
            }
        });
        comboAcesso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboAcessoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                comboAcessoKeyReleased(evt);
            }
        });

        labelBotao.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        labelBotao.setText("Aguardando...");
        labelBotao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                labelBotaoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                labelBotaoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNome)
                    .addComponent(labelSenha)
                    .addComponent(labelEmail)
                    .addComponent(labelAcesso))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(labelBotao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSenha)
                            .addComponent(txtUsuario)
                            .addComponent(txtEmail)
                            .addComponent(comboAcesso, 0, 141, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNome)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSenha)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAcesso)
                            .addComponent(comboAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(labelBotao)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(panelDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        sairTecla(evt);
        passaParaCombo(evt);
//        preencheTexto("\n");
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased

        sairTecla(evt);
        passaParaCombo(evt);

        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyReleased

    public void passaParaAcesso(KeyEvent ev){
        acesso = new Acesso();
        if(txtEmail.getText().length() > 5){
            if(ev.getKeyCode() == KeyEvent.VK_ENTER){
                preencheTexto(acesso.completaAcesso());
                
            }
        }        
    }
    public void passaParaCombo(KeyEvent ev){
        preencheTexto("\nSelecione o acesso e digite <ENTER>");
        if(txtEmail.getText().length() > 5){
            if(ev.getKeyCode() == KeyEvent.VK_ENTER){
                comboAcesso.requestFocus();
                
            }
        }        
    }
    
    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        sairTecla(evt);
        passaCampo(evt, txtEmail, txtSenha);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaKeyPressed

    private void txtSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyReleased
        sairTecla(evt);
        passaCampo(evt, txtEmail, txtSenha);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaKeyReleased

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        sairTecla(evt);
        passaCampo(evt, txtSenha, txtUsuario);

        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void txtUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyReleased
        sairTecla(evt);
        passaCampo(evt, txtSenha, txtUsuario);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioKeyReleased

    private void comboAcessoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboAcessoKeyPressed
        sairTecla(evt);
        labelBotao.setText(comboAcesso.getSelectedItem().toString());
//        preencheTexto("\nDigite's' para salvar ou 'n' para sair/ cancelar");
        labelBotao.requestFocus();        
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAcessoKeyPressed

    private void comboAcessoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboAcessoKeyReleased
        sairTecla(evt);
        labelBotao.setText(comboAcesso.getSelectedItem().toString());
//        preencheTexto("\nDigite's' para salvar ou 'n' para sair/ cancelar");
        labelBotao.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAcessoKeyReleased

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

//        String confirm = txtConfirma.getText();

        if(labelBotao.getText().equals(comboAcesso.getSelectedItem().toString())){
                if(evt.getKeyCode() == KeyEvent.VK_N){
                    sair();
                }
                if(evt.getKeyCode() == KeyEvent.VK_S){
                    salvaDados();
                }
    
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void comboAcessoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboAcessoMouseClicked
/*
        labelBotao.setText(comboAcesso.getSelectedItem().toString());
        //preencheTexto("\nDigite's' para salvar ou 'n' para sair/ cancelar");
        labelBotao.requestFocus();*/
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAcessoMouseClicked

    private void labelBotaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_labelBotaoKeyPressed

        if(!labelBotao.getText().equals("Aguardando...")){
            preencheTexto("\nDigite 's' para salvar ou 'n' para sair/ cancelar");
            
        }
        if(evt.getKeyCode() == KeyEvent.VK_N){
                    sair();
                }
                if(evt.getKeyCode() == KeyEvent.VK_S){
                    salvaDados();
                }
                // TODO add your handling code here:
    }//GEN-LAST:event_labelBotaoKeyPressed

    private void labelBotaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_labelBotaoKeyReleased
                if(evt.getKeyCode() == KeyEvent.VK_N){
                    sair();
                }
                if(evt.getKeyCode() == KeyEvent.VK_S){
                    salvaDados();
                }
                // TODO add your handling code here:
    }//GEN-LAST:event_labelBotaoKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        inicial.preencheCampo("\nCadastrado o usuário " + txtUsuario.getText());
        inicial.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    public void passaCampo(KeyEvent ev, JTextField campo, JTextField campoAnterior){
        if(ev.getKeyCode() == KeyEvent.VK_ENTER){
            if(campoAnterior.getText().isEmpty()){
//                preencheTexto("\nO campo não pode ficar vazio.");
                campoAnterior.requestFocus();
            }else{
                campo.setEditable(true);
                campo.requestFocus();
            }
        }        
    }
    
    public boolean validaCampos(JTextField campo){
        if(campo.getText().length() > 5){
            if(campo.getText().isEmpty()){
                preencheTexto("\nO campo não pode ficar vazio.");
                campo.setText("");
                campo.requestFocus();
                return false;
            }
        }
        return true;
    }
    
    public void sairTecla(KeyEvent ev){
        if(ev.getKeyCode() == KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }
    
    public String dataHoje(){
        int dia = cal.get(Calendar.DAY_OF_MONTH);
        int mes = cal.get(Calendar.MONTH) + 1;
        int ano = cal.get(Calendar.YEAR);
        
        String mesLongo = null;
        
        if(mes < 10){
            mesLongo = "0" + mes;
        }else{
            mesLongo = String.valueOf(mes);
        }
        
        String data = ano + "-" + mesLongo + "-" + dia;
        
        return data;
    }
    
    public void salvaDados(){
        
        int codAcesso = acesso.idComboAcesso((String) comboAcesso.getSelectedItem());
        user = new Usuario();
        acesso = new Acesso();
        user.setNome(txtUsuario.getText());
        user.setSenha(String.valueOf(txtSenha.getPassword()));
        user.setDataCadastro(dataHoje());
        user.setDataAlteracao(dataHoje());
        user.setEmail(txtEmail.getText());
        user.setCodAcesso(codAcesso);
        //user.incluirUsuario();
        preencheTexto("\nCadastro efetuado com sucesso.");
        preencheTexto("\nPressione <ESC> para sair.");
        limpaCampos();

    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DNovoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DNovoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DNovoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DNovoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DNovoUsuario dialog = new DNovoUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea campoTexto;
    private javax.swing.JComboBox<String> comboAcesso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAcesso;
    private javax.swing.JLabel labelBotao;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelTitilo2;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelDown;
    private javax.swing.JPanel panelTop;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
