/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistejm.telas;

import br.com.sistejm.classes.Agendamento;
import br.com.sistejm.classes.Configuracoes;
import br.com.sistejm.classes.Relatorios;
import java.awt.event.KeyEvent;
import javax.swing.JTextField;

/**
 *
 * @author Michel
 */
public class DRelAgendamento extends javax.swing.JDialog {

    Agendamento at;
    Configuracoes config;
    Relatorios rel;
    
    public String modelo;
    public String ordem;

    public String getModelo() {
        return modelo;
    }

    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    public String getOrdem() {
        return ordem;
    }

    public void setOrdem(String ordem) {
        this.ordem = ordem;
    }
    
    
    
    /**
     * Creates new form DRelAgendamento
     */
    public DRelAgendamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ativaPanelData(false);
//        ativaPanels(false);
//        preencheNome();
//        preencheCodigo();
        inicioPadrao();
    }
    
    public void ativaPanelData(boolean valor){
        panelData.setEnabled(valor);
    }
    
    public void inicioPadrao(){
        this.setOrdem("idagendamento");
        this.setModelo("nome");
    }
   
//    public void ativaPanels(boolean valor){
////        panelNome.setVisible(valor);
//        panelCodigo.setVisible(valor);
//        panelConsultor.setVisible(false);
//    }
    
    public void direcionaDataInicial(){
        txtDataInicial.requestFocus();
    }
    
    public void fechar(){
        this.dispose();
    }
    
//    public void preencheNome(){
//        at = new Agendamento();
//        at.preencheComboNome(comboNome);
//    }
//    public void preencheCodigo(){
//        at = new Agendamento();
//        at.preencheComboCodigo(comboCodigo);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        groupTpRel = new javax.swing.ButtonGroup();
        groupPeriodo = new javax.swing.ButtonGroup();
        panelDown = new javax.swing.JPanel();
        labelVersao = new javax.swing.JLabel();
        panelTop = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        btImprimir = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        panelData = new javax.swing.JPanel();
        txtDataFinal = new javax.swing.JTextField();
        labelAte = new javax.swing.JLabel();
        txtDataInicial = new javax.swing.JTextField();
        labelPeriodo = new javax.swing.JLabel();
        radioHoje = new javax.swing.JRadioButton();
        radioOutras = new javax.swing.JRadioButton();
        labelRelatorio = new javax.swing.JLabel();
        radioNome = new javax.swing.JRadioButton();
        radioConsultor = new javax.swing.JRadioButton();
        radioCodigo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaRelConsulta = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelDown.setBackground(new java.awt.Color(255, 255, 255));
        panelDown.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        labelVersao.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        labelVersao.setText("SISTEJM - Versão 1.0 - Interna");

        javax.swing.GroupLayout panelDownLayout = new javax.swing.GroupLayout(panelDown);
        panelDown.setLayout(panelDownLayout);
        panelDownLayout.setHorizontalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDownLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVersao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDownLayout.setVerticalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelVersao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelTop.setBackground(new java.awt.Color(255, 255, 255));
        panelTop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTitulo.setText("Relatório de Agendamento | Atendimento");

        btImprimir.setBackground(new java.awt.Color(255, 255, 255));
        btImprimir.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        btImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/print.png"))); // NOI18N
        btImprimir.setText("Imprimir");
        btImprimir.setToolTipText("Imprimir");
        btImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });

        btSair.setBackground(new java.awt.Color(255, 255, 255));
        btSair.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/cancelar.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.setToolTipText("Sair");
        btSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelData.setBackground(new java.awt.Color(255, 255, 255));
        panelData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        txtDataFinal.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtDataFinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDataFinalKeyReleased(evt);
            }
        });

        labelAte.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelAte.setText("até");

        txtDataInicial.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtDataInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDataInicialKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDataInicialKeyReleased(evt);
            }
        });

        labelPeriodo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelPeriodo.setText("Período:");

        radioHoje.setBackground(new java.awt.Color(255, 255, 255));
        groupPeriodo.add(radioHoje);
        radioHoje.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        radioHoje.setText("  Hoje");
        radioHoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioHojeActionPerformed(evt);
            }
        });

        radioOutras.setBackground(new java.awt.Color(255, 255, 255));
        groupPeriodo.add(radioOutras);
        radioOutras.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        radioOutras.setSelected(true);
        radioOutras.setText("  Outras datas (dd/mm/aaaa)");
        radioOutras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioOutrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDataLayout = new javax.swing.GroupLayout(panelData);
        panelData.setLayout(panelDataLayout);
        panelDataLayout.setHorizontalGroup(
            panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPeriodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDataLayout.createSequentialGroup()
                        .addComponent(txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelAte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDataLayout.createSequentialGroup()
                        .addComponent(radioHoje)
                        .addGap(18, 18, 18)
                        .addComponent(radioOutras)))
                .addContainerGap())
        );
        panelDataLayout.setVerticalGroup(
            panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioHoje)
                    .addComponent(radioOutras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAte)
                    .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPeriodo))
                .addGap(22, 22, 22))
        );

        labelRelatorio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelRelatorio.setText("Relatório por:");

        groupTpRel.add(radioNome);
        radioNome.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        radioNome.setSelected(true);
        radioNome.setText("   Nome");
        radioNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNomeActionPerformed(evt);
            }
        });

        groupTpRel.add(radioConsultor);
        radioConsultor.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        radioConsultor.setText("  Consultor");
        radioConsultor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioConsultorActionPerformed(evt);
            }
        });

        groupTpRel.add(radioCodigo);
        radioCodigo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        radioCodigo.setText("  Comprovante");
        radioCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCodigoActionPerformed(evt);
            }
        });

        tabelaRelConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaRelConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelRelatorio)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioConsultor)
                            .addComponent(radioNome)
                            .addComponent(radioCodigo))
                        .addGap(26, 26, 26)
                        .addComponent(panelData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRelatorio)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioConsultor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioCodigo))
                    .addComponent(panelData, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(panelDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed
        rel = new Relatorios();
        config = new Configuracoes();
        String valor = null;
        
//        if(this.modelo.equals("nome")){
//            valor = comboNome.getSelectedItem().toString();
//        }else if (this.modelo.equals("consultor")){
//            valor = comboConsultor.getSelectedItem().toString();
//        }else if (this.modelo.equals("codigo")){
//            valor = comboCodigo.getSelectedItem().toString();
//        }
        
        if(txtDataInicial.getText().equals("")){
            txtDataInicial.setText(config.retornaData());
        }
        if(txtDataFinal.getText().equals("")){
            txtDataFinal.setText(config.retornaData());
        }
        
        rel.geraRelatorioAgendamento(this.getModelo(), valor, config.retornaFormatoDataSQL(txtDataInicial.getText()), config.retornaFormatoDataSQL(txtDataFinal.getText()), this.getOrdem());

        // TODO add your handling code here:
    }//GEN-LAST:event_btImprimirActionPerformed

    private void txtDataInicialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataInicialKeyReleased

        mascaraData(txtDataInicial);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataInicialKeyReleased

    private void txtDataFinalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataFinalKeyReleased

        mascaraData(txtDataFinal);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataFinalKeyReleased

    private void txtDataInicialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataInicialKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtDataFinal.setText(txtDataInicial.getText());
            txtDataFinal.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataInicialKeyPressed

    private void radioNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNomeActionPerformed
//        ativaPanels(false);
//        panelNome.setVisible(true);
        direcionaDataInicial();
        this.setModelo("nome");
// TODO add your handling code here:
    }//GEN-LAST:event_radioNomeActionPerformed

    private void radioConsultorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioConsultorActionPerformed

//        panelNome.setVisible(false);
//        panelCodigo.setVisible(false);
//        panelConsultor.setVisible(true);
        direcionaDataInicial();
        this.setModelo("consultor");

        // TODO add your handling code here:
    }//GEN-LAST:event_radioConsultorActionPerformed

    private void radioCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCodigoActionPerformed

//        panelNome.setVisible(false);
//        panelConsultor.setVisible(false);
//        panelCodigo.setVisible(true);
        direcionaDataInicial();
        this.setModelo("codigo");
        // TODO add your handling code here:
    }//GEN-LAST:event_radioCodigoActionPerformed

    private void radioOutrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioOutrasActionPerformed

        txtDataInicial.setText("");
        txtDataFinal.setText("");
        txtDataInicial.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_radioOutrasActionPerformed

    private void radioHojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioHojeActionPerformed

        config = new Configuracoes();
        
        txtDataInicial.setText(config.retornaData());
        txtDataFinal.setText(config.retornaData());
        // TODO add your handling code here:
    }//GEN-LAST:event_radioHojeActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed

        this.fechar();
// TODO add your handling code here:
    }//GEN-LAST:event_btSairActionPerformed

    
    public void pesquisaPreRelatorio(){
        at = new Agendamento();
        
        switch(this.modelo){
            case "nome":
                
        }
        
        
        at.buscaTabAgendamento(tabelaRelConsulta, this.modelo, modelo, txtDataInicial.getText(), txtDataFinal.getText());
        //JTable tabela, String coluna, String valor, String data1, String data2
    }
    
    public void mascaraData(JTextField campo){
        if(campo.getText().length() == 2){
            campo.setText(campo.getText() + "/");
        }
        if(campo.getText().length() == 5){
            campo.setText(campo.getText() + "/");
        }        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DRelAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DRelAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DRelAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DRelAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DRelAgendamento dialog = new DRelAgendamento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btImprimir;
    private javax.swing.JButton btSair;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.ButtonGroup groupPeriodo;
    private javax.swing.ButtonGroup groupTpRel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAte;
    private javax.swing.JLabel labelPeriodo;
    private javax.swing.JLabel labelRelatorio;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelVersao;
    private javax.swing.JPanel panelData;
    private javax.swing.JPanel panelDown;
    private javax.swing.JPanel panelTop;
    private javax.swing.JRadioButton radioCodigo;
    private javax.swing.JRadioButton radioConsultor;
    private javax.swing.JRadioButton radioHoje;
    private javax.swing.JRadioButton radioNome;
    private javax.swing.JRadioButton radioOutras;
    private javax.swing.JTable tabelaRelConsulta;
    private javax.swing.JTextField txtDataFinal;
    private javax.swing.JTextField txtDataInicial;
    // End of variables declaration//GEN-END:variables
}
