/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistejm.telas;

import br.com.sistejm.classes.Configuracoes;
import br.com.sistejm.classes.Coroa;
import br.com.sistejm.classes.Mediuns;
import br.com.sistejm.classes.Mensalidade;
import br.com.sistejm.classes.Relatorios;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Michel
 */
public class DRelatorioMensalidade extends javax.swing.JDialog {

    private int codperiodo;
    private int mes1;
    private int mes2;
    private int ano1;
    private int ano2;
    private String tipo;
    private String medium;
    private int idMedium;
    
    Calendar cal;
    Mediuns m;
    Mensalidade men;
    Relatorios r;
    Configuracoes config;

    public String getMedium() {
        return medium;
    }

    public void setMedium(String medium) {
        this.medium = medium;
    }

    public int getIdMedium() {
        return idMedium;
    }

    public void setIdMediun(int idMedium) {
        this.idMedium = idMedium;
    }

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public int getMes1() {
        return mes1;
    }

    public void setMes1(int mes1) {
        this.mes1 = mes1;
    }

    public int getMes2() {
        return mes2;
    }

    public void setMes2(int mes2) {
        this.mes2 = mes2;
    }

    public int getAno1() {
        return ano1;
    }

    public void setAno1(int ano1) {
        this.ano1 = ano1;
    }

    public int getAno2() {
        return ano2;
    }

    public void setAno2(int ano2) {
        this.ano2 = ano2;
    }

    public int getCodperiodo() {
        return codperiodo;
    }

    public void setCodperiodo(int codperiodo) {
        this.codperiodo = codperiodo;
    }
    
    public void campoPeriodo(boolean valor){
        txtMesAno1.setText("");
        txtMesAno2.setText("");
        txtMesAno1.setEditable(valor);
        txtMesAno2.setEditable(valor);
    }
    
    public void campoMesAno(boolean valor){
        txtMesAno3.setText("");
        txtMesAno3.setEditable(valor);
    }
    
    public void campoAnoLetivo(boolean valor){
        txtAnoLetivo.setText("");
        txtAnoLetivo.setEditable(valor);
    }    
    
    /**
     * Creates new form DRelatorioMensalidade
     */
    public DRelatorioMensalidade(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        exibeTabMediuns();
        campoAnoLetivo(false);
        campoMesAno(false);
        campoPeriodo(false);
        exibeQuantidade();
    }
    
    public void exibeTabMediuns(){
        m = new Mediuns();
        m.preencheTaMediumNIsentos(tabelaMediuns);
    }
    
    public void exibeQuantidade(){
        if(radioAnalitico.isSelected()){
            this.tipo = "analitico";
            camposSintetico(false);
            labelQuantPagos.setText("0");
            labelQuantAtrasado.setText("0");

        }else if (radioSintetico.isSelected()){
            this.tipo = "analitico";
            camposSintetico(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupTipo = new javax.swing.ButtonGroup();
        groupMediuns = new javax.swing.ButtonGroup();
        groupPeriodo = new javax.swing.ButtonGroup();
        panelPeriodo = new javax.swing.JPanel();
        radioCorrente = new javax.swing.JRadioButton();
        txtMesAno3 = new javax.swing.JTextField();
        radioPeriodo = new javax.swing.JRadioButton();
        txtMesAno1 = new javax.swing.JTextField();
        txtMesAno2 = new javax.swing.JTextField();
        radioAno = new javax.swing.JRadioButton();
        txtAnoLetivo = new javax.swing.JTextField();
        panelCoroas = new javax.swing.JPanel();
        radioAnalitico = new javax.swing.JRadioButton();
        radioSintetico = new javax.swing.JRadioButton();
        panelMediuns = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMediuns = new javax.swing.JTable();
        txtNomeMedium = new javax.swing.JTextField();
        radioTodos = new javax.swing.JRadioButton();
        radioMediumEspec = new javax.swing.JRadioButton();
        panelDown = new javax.swing.JPanel();
        labelVersao = new javax.swing.JLabel();
        panelTop = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        btCancelar = new javax.swing.JButton();
        txtData = new javax.swing.JTextField();
        txtCodMedium = new javax.swing.JTextField();
        labelFotoCoroa = new javax.swing.JLabel();
        txtMes = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        btImprimir = new javax.swing.JButton();
        labelMesesAtrasado = new javax.swing.JLabel();
        labelQuantAtrasado = new javax.swing.JLabel();
        labelMesesPagos = new javax.swing.JLabel();
        labelQuantPagos = new javax.swing.JLabel();
        labelValorAtraso = new javax.swing.JLabel();
        labelValorPago = new javax.swing.JLabel();
        labelTotalPago = new javax.swing.JLabel();
        labelTotalNPago = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        labelPeriodo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelPeriodo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " PERÍODO ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        groupPeriodo.add(radioCorrente);
        radioCorrente.setText("Por mês e ano");
        radioCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCorrenteActionPerformed(evt);
            }
        });

        txtMesAno3.setText("mm/yyyy");
        txtMesAno3.setToolTipText("mm/yyyy");
        txtMesAno3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMesAno3MouseClicked(evt);
            }
        });
        txtMesAno3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMesAno3KeyReleased(evt);
            }
        });

        groupPeriodo.add(radioPeriodo);
        radioPeriodo.setText("Por período");
        radioPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPeriodoActionPerformed(evt);
            }
        });

        txtMesAno1.setText("mm/yyyy");
        txtMesAno1.setToolTipText("mm/yyyy");
        txtMesAno1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMesAno1MouseClicked(evt);
            }
        });
        txtMesAno1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMesAno1KeyReleased(evt);
            }
        });

        txtMesAno2.setText("mm/yyyy");
        txtMesAno2.setToolTipText("mm/yyyy");
        txtMesAno2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMesAno2MouseClicked(evt);
            }
        });
        txtMesAno2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMesAno2KeyReleased(evt);
            }
        });

        groupPeriodo.add(radioAno);
        radioAno.setText("Por ano");
        radioAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAnoActionPerformed(evt);
            }
        });

        txtAnoLetivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAnoLetivoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelPeriodoLayout = new javax.swing.GroupLayout(panelPeriodo);
        panelPeriodo.setLayout(panelPeriodoLayout);
        panelPeriodoLayout.setHorizontalGroup(
            panelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPeriodoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioCorrente)
                    .addComponent(radioPeriodo)
                    .addComponent(radioAno))
                .addGap(18, 18, 18)
                .addGroup(panelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAnoLetivo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPeriodoLayout.createSequentialGroup()
                        .addComponent(txtMesAno1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMesAno2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtMesAno3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPeriodoLayout.setVerticalGroup(
            panelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPeriodoLayout.createSequentialGroup()
                .addGroup(panelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAno)
                    .addComponent(txtAnoLetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioCorrente)
                    .addComponent(txtMesAno3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioPeriodo)
                    .addComponent(txtMesAno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMesAno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        panelCoroas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " TIPO ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        groupTipo.add(radioAnalitico);
        radioAnalitico.setSelected(true);
        radioAnalitico.setText("Analítico (Quantitativo)");
        radioAnalitico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAnaliticoActionPerformed(evt);
            }
        });

        groupTipo.add(radioSintetico);
        radioSintetico.setText("Sintético (Resumo)");
        radioSintetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSinteticoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCoroasLayout = new javax.swing.GroupLayout(panelCoroas);
        panelCoroas.setLayout(panelCoroasLayout);
        panelCoroasLayout.setHorizontalGroup(
            panelCoroasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoroasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCoroasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioAnalitico)
                    .addComponent(radioSintetico))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        panelCoroasLayout.setVerticalGroup(
            panelCoroasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoroasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioAnalitico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioSintetico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMediuns.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " MÉDIUNS ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        tabelaMediuns.setForeground(new java.awt.Color(0, 0, 102));
        tabelaMediuns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaMediuns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMediunsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaMediuns);

        txtNomeMedium.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeMediumKeyReleased(evt);
            }
        });

        groupMediuns.add(radioTodos);
        radioTodos.setSelected(true);
        radioTodos.setText("Todos");
        radioTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTodosActionPerformed(evt);
            }
        });

        groupMediuns.add(radioMediumEspec);
        radioMediumEspec.setText("Médium específico");
        radioMediumEspec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMediumEspecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMediunsLayout = new javax.swing.GroupLayout(panelMediuns);
        panelMediuns.setLayout(panelMediunsLayout);
        panelMediunsLayout.setHorizontalGroup(
            panelMediunsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMediunsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMediunsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panelMediunsLayout.createSequentialGroup()
                        .addGroup(panelMediunsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMediunsLayout.createSequentialGroup()
                                .addComponent(radioTodos)
                                .addGap(18, 18, 18)
                                .addComponent(radioMediumEspec))
                            .addComponent(txtNomeMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 143, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelMediunsLayout.setVerticalGroup(
            panelMediunsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMediunsLayout.createSequentialGroup()
                .addGroup(panelMediunsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioTodos)
                    .addComponent(radioMediumEspec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNomeMedium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDown.setBackground(new java.awt.Color(255, 255, 255));
        panelDown.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        labelVersao.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        labelVersao.setText("SISTEJM - Versão 1.0 - Interna");

        javax.swing.GroupLayout panelDownLayout = new javax.swing.GroupLayout(panelDown);
        panelDown.setLayout(panelDownLayout);
        panelDownLayout.setHorizontalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDownLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVersao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDownLayout.setVerticalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelVersao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelTop.setBackground(new java.awt.Color(255, 255, 255));
        panelTop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        labelTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelTitulo.setText("RELATÓRIO DE MENSALIDADES");

        btCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btCancelar.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/cancelar.png"))); // NOI18N
        btCancelar.setText("Sair");
        btCancelar.setToolTipText("Sair");
        btCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelar.setMaximumSize(new java.awt.Dimension(51, 43));
        btCancelar.setMinimumSize(new java.awt.Dimension(51, 43));
        btCancelar.setPreferredSize(new java.awt.Dimension(51, 43));
        btCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        txtData.setEditable(false);
        txtData.setToolTipText("Data");

        txtCodMedium.setEditable(false);
        txtCodMedium.setToolTipText("codMedium");

        labelFotoCoroa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/BtCoroa.png"))); // NOI18N

        txtMes.setEditable(false);
        txtMes.setToolTipText("Mes");

        txtAno.setEditable(false);
        txtAno.setToolTipText("Ano");

        btImprimir.setBackground(new java.awt.Color(255, 255, 255));
        btImprimir.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        btImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/print.png"))); // NOI18N
        btImprimir.setText("Imprimir");
        btImprimir.setToolTipText("Imprimir");
        btImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFotoCoroa)
                .addGap(18, 18, 18)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelTopLayout.createSequentialGroup()
                        .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(panelTopLayout.createSequentialGroup()
                        .addComponent(txtData)
                        .addGap(18, 18, 18)))
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCodMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(txtMes, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelFotoCoroa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTopLayout.createSequentialGroup()
                        .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodMedium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btImprimir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        labelMesesAtrasado.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelMesesAtrasado.setForeground(new java.awt.Color(204, 0, 0));
        labelMesesAtrasado.setText("Meses em atraso:");

        labelQuantAtrasado.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelQuantAtrasado.setForeground(new java.awt.Color(204, 0, 0));
        labelQuantAtrasado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelQuantAtrasado.setText("0");

        labelMesesPagos.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelMesesPagos.setForeground(new java.awt.Color(0, 0, 153));
        labelMesesPagos.setText("Meses pagos:");

        labelQuantPagos.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelQuantPagos.setForeground(new java.awt.Color(0, 0, 153));
        labelQuantPagos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelQuantPagos.setText("0");

        labelValorAtraso.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelValorAtraso.setForeground(new java.awt.Color(204, 0, 0));
        labelValorAtraso.setText("Valor (R$):");

        labelValorPago.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelValorPago.setForeground(new java.awt.Color(0, 0, 153));
        labelValorPago.setText("Valor (R$):");

        labelTotalPago.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelTotalPago.setForeground(new java.awt.Color(0, 0, 153));
        labelTotalPago.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTotalPago.setText("0,00");

        labelTotalNPago.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelTotalNPago.setForeground(new java.awt.Color(204, 0, 0));
        labelTotalNPago.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTotalNPago.setText("0,00");

        labelTipo.setText("Tipo");

        labelPeriodo.setText("Período");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDown, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCoroas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPeriodo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(labelMesesPagos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelQuantPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(labelMesesAtrasado)
                                .addGap(18, 18, 18)
                                .addComponent(labelQuantAtrasado, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelValorAtraso)
                                .addGap(18, 18, 18)
                                .addComponent(labelTotalNPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelValorPago)
                                .addGap(18, 18, 18)
                                .addComponent(labelTotalPago, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(panelMediuns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTipo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(panelCoroas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(panelPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(panelMediuns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTipo)
                        .addGap(18, 18, 18)
                        .addComponent(labelPeriodo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMesesPagos)
                    .addComponent(labelQuantPagos)
                    .addComponent(labelValorPago)
                    .addComponent(labelTotalPago))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMesesAtrasado)
                    .addComponent(labelQuantAtrasado)
                    .addComponent(labelValorAtraso)
                    .addComponent(labelTotalNPago))
                .addGap(18, 18, 18)
                .addComponent(panelDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCorrenteActionPerformed

        this.codperiodo = 2;
        campoPeriodo(false);
        campoMesAno(true);
        campoAnoLetivo(false);
        txtMesAno3.requestFocus();
    }//GEN-LAST:event_radioCorrenteActionPerformed

    private void txtMesAno3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMesAno3MouseClicked
        txtMesAno3.setText("");
    }//GEN-LAST:event_txtMesAno3MouseClicked

    public void recebeInfo(String user){
        config = new Configuracoes();
        config.gravaAtividades("Abertura de relatório de mensalidades", user, "Relatório Geral de Mensalidade");
    }    
    
    private void txtMesAno3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesAno3KeyReleased
        if(txtMesAno3.getText().length() == 2){
            txtMesAno3.setText(txtMesAno3.getText() + "/");
        }
        if(txtMesAno3.getText().length() == 7){
            int mes = Integer.valueOf(txtMesAno3.getText().substring(0, 2));
            int ano = Integer.valueOf(txtMesAno3.getText().substring(3, 7));
            this.mes1 = mes;
            this.ano1 = ano;
            this.mes2 = 0;
            this.ano2 = 0;

            labelPeriodo.setText("Por Mês/ Ano " + txtMesAno3.getText());
            txtAno.setText(String.valueOf(ano));
            
            verificaQuantidadeAnalitico();
        }
    }//GEN-LAST:event_txtMesAno3KeyReleased

    private void radioPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPeriodoActionPerformed
        this.codperiodo = 3;
        txtMesAno1.setText("");
        txtMesAno2.setText("");
        txtMesAno1.requestFocus();
        campoPeriodo(true);
        campoMesAno(false);
        campoAnoLetivo(false);
    }//GEN-LAST:event_radioPeriodoActionPerformed

    private void txtMesAno1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMesAno1MouseClicked
        txtMesAno1.setText("");
    }//GEN-LAST:event_txtMesAno1MouseClicked

    private void txtMesAno1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesAno1KeyReleased

        if(txtMesAno1.getText().length() == 2){
            txtMesAno1.setText(txtMesAno1.getText() + "/");
        }
        if(txtMesAno1.getText().length() == 7){
            this.mes1 = Integer.valueOf(txtMesAno1.getText().substring(0, 2));
            this.ano1 = Integer.valueOf(txtMesAno1.getText().substring(3, 7));
            this.mes2 = 0;
            this.ano2 = 0;

            txtMesAno2.requestFocus();
        }
    }//GEN-LAST:event_txtMesAno1KeyReleased

    private void txtMesAno2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMesAno2MouseClicked
        txtMesAno2.setText("");
    }//GEN-LAST:event_txtMesAno2MouseClicked

    private void txtMesAno2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesAno2KeyReleased

        if(txtMesAno1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo de período inicial não pode ficar vazio");
        }else{
            if(txtMesAno2.getText().length() == 2){
                txtMesAno2.setText(txtMesAno2.getText() + "/");
            }
            if(txtMesAno2.getText().length() == 7){
                this.mes1 = Integer.valueOf(txtMesAno1.getText().substring(0, 2));
                this.ano1 = Integer.valueOf(txtMesAno1.getText().substring(3, 7));

                this.mes2 = Integer.valueOf(txtMesAno2.getText().substring(0, 2));
                this.ano2 = Integer.valueOf(txtMesAno2.getText().substring(3, 7));
                labelPeriodo.setText("Por período de " + txtMesAno1.getText() + " a " + txtMesAno2.getText());
                verificaQuantidadeAnalitico();

                if(this.tipo.equals("sintetico")){
                    verificaQuantidadeSintetico();
                }
                
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesAno2KeyReleased

    private void radioAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAnoActionPerformed

        this.codperiodo = 1;
        campoAnoLetivo(true);
        txtAnoLetivo.setText(txtAno.getText());
        txtAnoLetivo.requestFocus();
        campoMesAno(false);
        campoPeriodo(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_radioAnoActionPerformed

    private void radioAnaliticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAnaliticoActionPerformed

        String analitico = "Analítico";
        labelTipo.setText(analitico.toUpperCase());
        this.setTipo("analitico");
        camposSintetico(false);
        verificaQuantidadeAnalitico();
        campoAnoLetivo(true);
        txtAnoLetivo.setText(txtAno.getText());
        txtAnoLetivo.requestFocus();
        campoMesAno(false);
        campoPeriodo(false);        
    }//GEN-LAST:event_radioAnaliticoActionPerformed

    private void radioSinteticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSinteticoActionPerformed
        String sintetico = "Sintético";
        labelTipo.setText(sintetico.toUpperCase());
        this.tipo = "sintetico";
        camposSintetico(true);
        campoAnoLetivo(true);
        txtAnoLetivo.setText(txtAno.getText());
        txtAnoLetivo.requestFocus();
        campoMesAno(false);
        campoPeriodo(false);        
        verificaQuantidadeSintetico();

    }//GEN-LAST:event_radioSinteticoActionPerformed

    public void camposSintetico(boolean valor){

        labelValorPago.setVisible(valor);
        labelValorAtraso.setVisible(valor);
        labelTotalNPago.setVisible(valor);
        labelTotalPago.setVisible(valor);
        
    }

    
    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        fechar();
    }//GEN-LAST:event_btCancelarActionPerformed

    public void fechar(){
        this.setAutoRequestFocus(false);
        this.dispose();
    }
    
    public void verificaQuantidadeAnalitico(){
        men = new Mensalidade();
        cal = new GregorianCalendar();
        
        String anoCorrente = String.valueOf(cal.get(Calendar.YEAR));

        labelQuantPagos.setText("0");
        labelQuantAtrasado.setText("0");
        
        //Preenche periodo padronizado
        if(labelPeriodo.getText().equals("Período")){
            txtAno.setText(anoCorrente);
            this.ano1 = cal.get(Calendar.YEAR);
            labelPeriodo.setText("POR ANO " + txtAno.getText());
            radioAnalitico.setSelected(true);
            txtAnoLetivo.setEnabled(true);
        }
        //Verifica nome do médium
        if(!txtNomeMedium.getText().equals("") && !txtNomeMedium.getText().equals("Todos")){
            txtCodMedium.setText(String.valueOf(m.retornaIdMedium(txtNomeMedium.getText())));
        }else{
            txtCodMedium.setText("0");
        }
        labelQuantAtrasado.setText(String.valueOf(men.quantMeses("n", Integer.valueOf(txtCodMedium.getText()), 
        this.codperiodo, this.mes1, this.ano1, this.mes2, this.ano2)));

        labelQuantPagos.setText(String.valueOf(men.quantMeses("s", Integer.valueOf(txtCodMedium.getText()), 
        this.codperiodo, this.mes1, this.ano1, this.mes2, this.ano2)));
    }    
    public void verificaQuantidadeSintetico(){
            men = new Mensalidade();
            men.setAno(Integer.valueOf(txtAno.getText()));
            if(!txtNomeMedium.getText().equals("") && !txtNomeMedium.getText().equals("Todos")){
                txtCodMedium.setText(String.valueOf(m.retornaIdMedium(txtNomeMedium.getText())));
                men.setCodMedium(Integer.valueOf(txtCodMedium.getText()));
            }else{
                txtCodMedium.setText("0");
                men.setCodMedium(0);
            }
            labelQuantAtrasado.setText(String.valueOf(men.retornaQuantNPagosSintetico()));
            labelQuantPagos.setText(String.valueOf(men.retornaQuantPagosSintetico()));
            labelTotalNPago.setText(String.valueOf(men.retornaValoresNPagosSintetico()));
            labelTotalPago.setText(String.valueOf(men.retornaValoresPagosSintetico()));

    }    
    
    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed

        if(this.tipo.equals("analitico")){
            if(labelTipo.getText().equals("Tipo")){
                JOptionPane.showMessageDialog(null, "Selecione o tipo de relatório", "ERROR", JOptionPane.WARNING_MESSAGE);
            }
            if(txtNomeMedium.getText().equals("Médiuns")){
                JOptionPane.showMessageDialog(null, "Selecione todos ou médium específico", "ERROR", JOptionPane.WARNING_MESSAGE);
            }
            if(labelPeriodo.getText().equals("Período")){
                JOptionPane.showMessageDialog(null, "Selecione e digite o período", "ERROR", JOptionPane.WARNING_MESSAGE);
            }

            if(this.codperiodo == 3){
                if(txtMesAno2.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Preencha o segundo campo do mês/ ano", "ERROR", JOptionPane.WARNING_MESSAGE);
                    txtMesAno2.setText("");
                    txtMesAno2.requestFocus();
                }
            }
        }else if(this.tipo.equals("sintetico")){
            if(this.codperiodo == 0){
                this.ano1 = Integer.valueOf(txtAno.getText());
                this.codperiodo = 1;
            }
            if(txtCodMedium.getText().equals("")){
                txtCodMedium.setText("0");
            }
        }

            r = new Relatorios();
            r.relatorioMensalidade(this.tipo, Integer.valueOf(txtCodMedium.getText()),
                this.codperiodo, this.mes1, this.ano1, this.mes2, this.ano2);

        // TODO add your handling code here:
    }//GEN-LAST:event_btImprimirActionPerformed

    private void txtAnoLetivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnoLetivoKeyReleased

        if(txtAnoLetivo.getText().length() == 4){
            String periodo = "Por ano " + txtAnoLetivo.getText();
            txtAno.setText(txtAnoLetivo.getText());

            this.ano1 = Integer.valueOf(txtAnoLetivo.getText());
            labelPeriodo.setText(periodo.toUpperCase());
            if(this.tipo.equals("analitico")){
                verificaQuantidadeAnalitico();
            }else if(this.tipo.equals("sintetico")){
                verificaQuantidadeSintetico();
            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoLetivoKeyReleased

    private void tabelaMediunsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMediunsMouseClicked

        m = new Mediuns();
        String nomeMedium = String.valueOf(tabelaMediuns.getValueAt(tabelaMediuns.getSelectedRow(), 0));
        txtNomeMedium.setText(nomeMedium);
        this.medium = nomeMedium;
        txtCodMedium.setText(String.valueOf(m.retornaIdMedium(nomeMedium)));
        if(this.tipo.equals("analitico")){
            verificaQuantidadeAnalitico();
        }else if(this.tipo.equals("sintetico")){
            verificaQuantidadeSintetico();
        }

//        men = new Mensalidade();
//        men.setCodMedium(Integer.valueOf(txtCodMedium.getText()));
//        men.setAno(Integer.valueOf(txtAno.getText()));
//        men.consultaMesesPagos(cJan, cFev, cMar, cAbr,
//            cMai, cJun, cJul, cAgo, cSet, cOut,
//            cNov, cDez);

    }//GEN-LAST:event_tabelaMediunsMouseClicked

    private void txtNomeMediumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeMediumKeyReleased
    m = new Mediuns();
    m.buscaTabNomeMedium(tabelaMediuns, txtNomeMedium.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeMediumKeyReleased

    private void radioTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTodosActionPerformed

        this.medium = "Todos";
        txtNomeMedium.setText("Todos");
        // TODO add your handling code here:
    }//GEN-LAST:event_radioTodosActionPerformed

    private void radioMediumEspecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMediumEspecActionPerformed

        this.medium = "especifico";
        txtNomeMedium.setText("");
        txtNomeMedium.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMediumEspecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DRelatorioMensalidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DRelatorioMensalidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DRelatorioMensalidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DRelatorioMensalidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DRelatorioMensalidade dialog = new DRelatorioMensalidade(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btImprimir;
    private javax.swing.ButtonGroup groupMediuns;
    private javax.swing.ButtonGroup groupPeriodo;
    private javax.swing.ButtonGroup groupTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFotoCoroa;
    private javax.swing.JLabel labelMesesAtrasado;
    private javax.swing.JLabel labelMesesPagos;
    private javax.swing.JLabel labelPeriodo;
    private javax.swing.JLabel labelQuantAtrasado;
    private javax.swing.JLabel labelQuantPagos;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTotalNPago;
    private javax.swing.JLabel labelTotalPago;
    private javax.swing.JLabel labelValorAtraso;
    private javax.swing.JLabel labelValorPago;
    private javax.swing.JLabel labelVersao;
    private javax.swing.JPanel panelCoroas;
    private javax.swing.JPanel panelDown;
    private javax.swing.JPanel panelMediuns;
    private javax.swing.JPanel panelPeriodo;
    private javax.swing.JPanel panelTop;
    private javax.swing.JRadioButton radioAnalitico;
    private javax.swing.JRadioButton radioAno;
    private javax.swing.JRadioButton radioCorrente;
    private javax.swing.JRadioButton radioMediumEspec;
    private javax.swing.JRadioButton radioPeriodo;
    private javax.swing.JRadioButton radioSintetico;
    private javax.swing.JRadioButton radioTodos;
    private javax.swing.JTable tabelaMediuns;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtAnoLetivo;
    private javax.swing.JTextField txtCodMedium;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtMesAno1;
    private javax.swing.JTextField txtMesAno2;
    private javax.swing.JTextField txtMesAno3;
    private javax.swing.JTextField txtNomeMedium;
    // End of variables declaration//GEN-END:variables
}
