/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistejm.telas;

import br.com.sistejm.classes.Coroa;
import br.com.sistejm.classes.Mediuns;
import br.com.sistejm.classes.Relatorios;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Michel
 */
public class DRelatorioCoroa extends javax.swing.JDialog {

    Calendar cal;
    Mediuns m;
    Relatorios r;
    Coroa c;
    
    private int idMedium;
    private int mes1;
    private int mes2;
    private int ano1;
    private int ano2;
    private int codperiodo;
    private String confirma;
    private int iduser;
    private String user;

    public int getIduser() {
        return iduser;
    }

    public void setIduser(int iduser) {
        this.iduser = iduser;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }
    

    public int getCodperiodo() {
        return codperiodo;
    }

    public void setCodperiodo(int codperiodo) {
        this.codperiodo = codperiodo;
    }

    public int getMes1() {
        return mes1;
    }

    public void setMes1(int mes1) {
        this.mes1 = mes1;
    }

    public int getMes2() {
        return mes2;
    }

    public void setMes2(int mes2) {
        this.mes2 = mes2;
    }

    public int getAno1() {
        return ano1;
    }

    public void setAno1(int ano1) {
        this.ano1 = ano1;
    }

    public int getAno2() {
        return ano2;
    }

    public void setAno2(int ano2) {
        this.ano2 = ano2;
    }

    public int getIdMedium() {
        return idMedium;
    }

    public void setIdMedium(int idMedium) {
        this.idMedium = idMedium;
    }

    public String getConfirma() {
        return confirma;
    }

    public void setConfirma(String confirma) {
        this.confirma = confirma;
    }
    
    /**
     * Creates new form DImprimeCoroa
     */
    public DRelatorioCoroa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        anoLetivo();
        preencheComboMediuns();
        comboMediuns.setVisible(false);
        ocultaText(false);
        txtIsEdit(false);
    }
    
    public void txtIsEdit(boolean valor){
        txtMesAno1.setEditable(valor);
        txtMesAno2.setEditable(valor);
        txtMesAno3.setEditable(valor);
    }
    public void preencheComboMediuns(){
        m = new Mediuns();
        m.preencheComboMedium(comboMediuns);
    }
    
    public void anoLetivo(){
        cal = new GregorianCalendar();
        int ano = cal.get(Calendar.YEAR);
        txtAnoLetivo.setText(String.valueOf(ano));
        txtAnoLetivo.setEditable(false);
    }
    
    public void ocultaText(boolean valor){
        txtData.setVisible(valor);
//        txtCodTpCoroa.setVisible(valor);
        txtCodMedium.setVisible(valor);
        txtAno.setVisible(valor);
        txtMes.setVisible(valor);
        
    }
    
    public void recebeInfo(int iduser, String user){
        this.iduser = iduser;
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupCoroas = new javax.swing.ButtonGroup();
        groupPeriodo = new javax.swing.ButtonGroup();
        groupMedium = new javax.swing.ButtonGroup();
        panelTop = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        btCancelar = new javax.swing.JButton();
        txtData = new javax.swing.JTextField();
        txtCodMedium = new javax.swing.JTextField();
        labelFotoCoroa = new javax.swing.JLabel();
        txtMes = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        btImprimir = new javax.swing.JButton();
        panelDown = new javax.swing.JPanel();
        labelVersao = new javax.swing.JLabel();
        panelCoroas = new javax.swing.JPanel();
        radioNConfirmados = new javax.swing.JRadioButton();
        radioConfirmados = new javax.swing.JRadioButton();
        panelPeriodo = new javax.swing.JPanel();
        radioCorrente = new javax.swing.JRadioButton();
        txtMesAno3 = new javax.swing.JTextField();
        radioPeriodo = new javax.swing.JRadioButton();
        txtMesAno1 = new javax.swing.JTextField();
        txtMesAno2 = new javax.swing.JTextField();
        radioProximos = new javax.swing.JRadioButton();
        txtAnoLetivo = new javax.swing.JTextField();
        panelMediuns = new javax.swing.JPanel();
        radioTodosM = new javax.swing.JRadioButton();
        radioMEspecif = new javax.swing.JRadioButton();
        comboMediuns = new javax.swing.JComboBox<>();
        labelCoroa = new javax.swing.JLabel();
        labelPeriodo = new javax.swing.JLabel();
        labelMediuns = new javax.swing.JLabel();
        labelPreQuantidade = new javax.swing.JLabel();
        labelValor = new javax.swing.JLabel();
        labelRegistros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelTop.setBackground(new java.awt.Color(255, 255, 255));
        panelTop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        labelTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelTitulo.setText("RELATÓRIO COROAÇÃO | SAÍDAS");

        btCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btCancelar.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/cancelar.png"))); // NOI18N
        btCancelar.setText("Sair");
        btCancelar.setToolTipText("Sair");
        btCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelar.setMaximumSize(new java.awt.Dimension(51, 43));
        btCancelar.setMinimumSize(new java.awt.Dimension(51, 43));
        btCancelar.setPreferredSize(new java.awt.Dimension(51, 43));
        btCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        txtData.setEditable(false);

        txtCodMedium.setEditable(false);
        txtCodMedium.setText("codMedium");

        labelFotoCoroa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/BtCoroa.png"))); // NOI18N

        txtMes.setEditable(false);

        txtAno.setEditable(false);

        btImprimir.setBackground(new java.awt.Color(255, 255, 255));
        btImprimir.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        btImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/print.png"))); // NOI18N
        btImprimir.setText("Imprimir");
        btImprimir.setToolTipText("Imprimir");
        btImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFotoCoroa)
                .addGap(18, 18, 18)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelTopLayout.createSequentialGroup()
                        .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(panelTopLayout.createSequentialGroup()
                        .addComponent(txtData)
                        .addGap(18, 18, 18)))
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCodMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(txtMes, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelFotoCoroa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTopLayout.createSequentialGroup()
                        .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodMedium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btImprimir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelDown.setBackground(new java.awt.Color(255, 255, 255));
        panelDown.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        labelVersao.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        labelVersao.setText("SISTEJM - Versão 1.0 - Interna");

        javax.swing.GroupLayout panelDownLayout = new javax.swing.GroupLayout(panelDown);
        panelDown.setLayout(panelDownLayout);
        panelDownLayout.setHorizontalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDownLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVersao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDownLayout.setVerticalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelVersao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelCoroas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Corôas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        groupCoroas.add(radioNConfirmados);
        radioNConfirmados.setText("Não confirmados");
        radioNConfirmados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNConfirmadosActionPerformed(evt);
            }
        });

        groupCoroas.add(radioConfirmados);
        radioConfirmados.setText("Confirmados");
        radioConfirmados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioConfirmadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCoroasLayout = new javax.swing.GroupLayout(panelCoroas);
        panelCoroas.setLayout(panelCoroasLayout);
        panelCoroasLayout.setHorizontalGroup(
            panelCoroasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoroasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCoroasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioNConfirmados)
                    .addComponent(radioConfirmados))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        panelCoroasLayout.setVerticalGroup(
            panelCoroasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoroasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioNConfirmados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioConfirmados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPeriodo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Período", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        groupPeriodo.add(radioCorrente);
        radioCorrente.setText("Por mês e ano");
        radioCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCorrenteActionPerformed(evt);
            }
        });

        txtMesAno3.setText("mm/yyyy");
        txtMesAno3.setToolTipText("mm/yyyy");
        txtMesAno3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMesAno3MouseClicked(evt);
            }
        });
        txtMesAno3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMesAno3KeyReleased(evt);
            }
        });

        groupPeriodo.add(radioPeriodo);
        radioPeriodo.setText("Por período");
        radioPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPeriodoActionPerformed(evt);
            }
        });

        txtMesAno1.setText("mm/yyyy");
        txtMesAno1.setToolTipText("mm/yyyy");
        txtMesAno1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMesAno1MouseClicked(evt);
            }
        });
        txtMesAno1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMesAno1KeyReleased(evt);
            }
        });

        txtMesAno2.setText("mm/yyyy");
        txtMesAno2.setToolTipText("mm/yyyy");
        txtMesAno2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMesAno2MouseClicked(evt);
            }
        });
        txtMesAno2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMesAno2KeyReleased(evt);
            }
        });

        groupPeriodo.add(radioProximos);
        radioProximos.setText("Próximos 3 meses  do ano ");
        radioProximos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioProximosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPeriodoLayout = new javax.swing.GroupLayout(panelPeriodo);
        panelPeriodo.setLayout(panelPeriodoLayout);
        panelPeriodoLayout.setHorizontalGroup(
            panelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPeriodoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPeriodoLayout.createSequentialGroup()
                        .addGroup(panelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioCorrente)
                            .addComponent(radioPeriodo))
                        .addGap(18, 18, 18)
                        .addGroup(panelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPeriodoLayout.createSequentialGroup()
                                .addComponent(txtMesAno1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMesAno2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtMesAno3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPeriodoLayout.createSequentialGroup()
                        .addComponent(radioProximos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAnoLetivo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPeriodoLayout.setVerticalGroup(
            panelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPeriodoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioProximos)
                    .addComponent(txtAnoLetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioCorrente)
                    .addComponent(txtMesAno3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioPeriodo)
                    .addComponent(txtMesAno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMesAno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        panelMediuns.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Médiuns", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        groupMedium.add(radioTodosM);
        radioTodosM.setText("Todos");
        radioTodosM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTodosMActionPerformed(evt);
            }
        });

        groupMedium.add(radioMEspecif);
        radioMEspecif.setText("De um médium especifico");
        radioMEspecif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMEspecifActionPerformed(evt);
            }
        });

        comboMediuns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboMediunsMouseClicked(evt);
            }
        });
        comboMediuns.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                comboMediunsPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout panelMediunsLayout = new javax.swing.GroupLayout(panelMediuns);
        panelMediuns.setLayout(panelMediunsLayout);
        panelMediunsLayout.setHorizontalGroup(
            panelMediunsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMediunsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMediunsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboMediuns, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelMediunsLayout.createSequentialGroup()
                        .addGroup(panelMediunsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioTodosM)
                            .addComponent(radioMEspecif))
                        .addGap(0, 79, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelMediunsLayout.setVerticalGroup(
            panelMediunsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMediunsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioTodosM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioMEspecif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboMediuns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        labelCoroa.setText("Corôas");

        labelPeriodo.setText("Período");

        labelMediuns.setText("Médiuns");

        labelPreQuantidade.setText("Quantidade: ");

        labelValor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelValor.setText("0");

        labelRegistros.setText("registros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(panelCoroas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelMediuns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCoroa)
                    .addComponent(labelPeriodo)
                    .addComponent(labelMediuns)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPreQuantidade)
                        .addGap(18, 18, 18)
                        .addComponent(labelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelRegistros)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(labelCoroa)
                        .addGap(18, 18, 18)
                        .addComponent(labelPeriodo)
                        .addGap(18, 18, 18)
                        .addComponent(labelMediuns)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPreQuantidade)
                            .addComponent(labelValor)
                            .addComponent(labelRegistros)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelCoroas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelMediuns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        fechar();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void radioCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCorrenteActionPerformed

        this.codperiodo = 2;
        campoPeriodo(false);
        campoMesAno(true);
        txtMesAno3.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_radioCorrenteActionPerformed

    public void campoPeriodo(boolean valor){
        txtMesAno1.setText("");
        txtMesAno2.setText("");
        txtMesAno1.setEditable(valor);
        txtMesAno2.setEditable(valor);
    }

    public void campoMesAno(boolean valor){
        txtMesAno3.setText("");
        txtMesAno3.setEditable(valor);
    }

    
    private void txtMesAno3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMesAno3MouseClicked

        txtMesAno3.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesAno3MouseClicked

    private void txtMesAno3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesAno3KeyReleased
        if(txtMesAno3.getText().length() == 2){
            txtMesAno3.setText(txtMesAno3.getText() + "/");
        }
        if(txtMesAno3.getText().length() == 7){
            int mes = Integer.valueOf(txtMesAno3.getText().substring(0, 2));
            int ano = Integer.valueOf(txtMesAno3.getText().substring(3, 7));
            this.mes1 = mes;
            this.ano1 = ano;
            this.mes2 = 0;
            this.ano2 = 0;
            
            labelPeriodo.setText("Por Mês/ Ano " + txtMesAno3.getText());
            verificaQuantidade();
            

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesAno3KeyReleased

    private void radioPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPeriodoActionPerformed
        this.codperiodo = 3;
        txtMesAno1.setText("");
        txtMesAno2.setText("");
        txtMesAno1.requestFocus();
        campoPeriodo(true);
        campoMesAno(false);
//        limpaLabels();

        // TODO add your handling code here:
    }//GEN-LAST:event_radioPeriodoActionPerformed

    private void txtMesAno1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesAno1KeyReleased

        if(txtMesAno1.getText().length() == 2){
            txtMesAno1.setText(txtMesAno1.getText() + "/");
        }
        if(txtMesAno1.getText().length() == 7){
            this.mes1 = Integer.valueOf(txtMesAno1.getText().substring(0, 2));
            this.ano1 = Integer.valueOf(txtMesAno1.getText().substring(3, 7));
            this.mes2 = 0;
            this.ano2 = 0;
            
            txtMesAno2.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesAno1KeyReleased

    private void txtMesAno2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesAno2KeyReleased

        if(txtMesAno1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campode período inicial não pode ficar vazio");
        }else{
            if(txtMesAno2.getText().length() == 2){
                txtMesAno2.setText(txtMesAno2.getText() + "/");
            }
            if(txtMesAno2.getText().length() == 7){
            this.mes1 = Integer.valueOf(txtMesAno1.getText().substring(0, 2));
            this.ano1 = Integer.valueOf(txtMesAno1.getText().substring(3, 7));
            
            this.mes2 = Integer.valueOf(txtMesAno2.getText().substring(0, 2));
            this.ano2 = Integer.valueOf(txtMesAno2.getText().substring(3, 7));                
            labelPeriodo.setText("Por período de " + txtMesAno1.getText() + " a " + txtMesAno2.getText());
            verificaQuantidade();
            
    //            c = new Coroa();
    //            int mes1 = Integer.valueOf(txtMesAno1.getText().substring(0, 2));
    //            int ano1 = Integer.valueOf(txtMesAno1.getText().substring(3, 7));
    //            int mes2 = Integer.valueOf(txtMesAno2.getText().substring(0, 2));
    //            int ano2 = Integer.valueOf(txtMesAno2.getText().substring(3, 7));
    //            c.preencheTabSaidasPeriodo(tabMedSaida, mes1, ano1, mes2, ano2);

            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesAno2KeyReleased

    private void comboMediunsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_comboMediunsPropertyChange

//        String mediumSelecionado = comboMediuns.getSelectedItem().toString();
//        labelMediuns.setText(mediumSelecionado);
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMediunsPropertyChange

    private void radioNConfirmadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNConfirmadosActionPerformed

        String nConfirmados = "Não Confirmados";
        labelCoroa.setText(nConfirmados.toUpperCase());
        this.setConfirma("n");
        verificaQuantidade();

    }//GEN-LAST:event_radioNConfirmadosActionPerformed

    private void radioConfirmadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioConfirmadosActionPerformed
        String confirmados = "Confirmados";
        labelCoroa.setText(confirmados.toUpperCase());
        this.setConfirma("s");
        verificaQuantidade();

    }//GEN-LAST:event_radioConfirmadosActionPerformed

    private void radioTodosMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTodosMActionPerformed
        String todos = "Todos";
        labelMediuns.setText(todos.toUpperCase());
        txtCodMedium.setText("0");
        verificaQuantidade();

        // TODO add your handling code here:
    }//GEN-LAST:event_radioTodosMActionPerformed

    private void radioMEspecifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMEspecifActionPerformed

        comboMediuns.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMEspecifActionPerformed

    private void radioProximosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioProximosActionPerformed

        cal = new GregorianCalendar();
        this.codperiodo = 1;
        String periodo = "Próximos 3 mes do ano " + txtAnoLetivo.getText();
        
        this.mes1 = cal.get(Calendar.MONTH) + 1;
        this.mes2 = this.mes1 + 3;
        
        this.ano1 = cal.get(Calendar.YEAR);
        labelPeriodo.setText(periodo.toUpperCase());
        verificaQuantidade();

        // TODO add your handling code here:
    }//GEN-LAST:event_radioProximosActionPerformed

    private void comboMediunsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMediunsMouseClicked

        m = new Mediuns();
        this.idMedium = m.retornaIdMedium(comboMediuns.getSelectedItem().toString());
        labelMediuns.setText("Do médium " + comboMediuns.getSelectedItem().toString());
        verificaQuantidade();

        // TODO add your handling code here:
    }//GEN-LAST:event_comboMediunsMouseClicked

    private void txtMesAno1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMesAno1MouseClicked
        txtMesAno1.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesAno1MouseClicked

    private void txtMesAno2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMesAno2MouseClicked
        txtMesAno2.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesAno2MouseClicked

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed

        if(labelCoroa.getText().equals("Corôas")){
            JOptionPane.showMessageDialog(null, "Selecione corôas confirmadas ou não", "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        if(labelMediuns.getText().equals("Médiuns")){
            JOptionPane.showMessageDialog(null, "Selecione todos ou médium específico", "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        if(labelPeriodo.getText().equals("Período")){
            JOptionPane.showMessageDialog(null, "Selecione e digite o período", "ERROR", JOptionPane.WARNING_MESSAGE);
        }

        if(!labelCoroa.getText().equals("Corôas") || !labelMediuns.getText().equals("Médiuns") || !labelPeriodo.getText().equals("Período")){
            r = new Relatorios();
            r.relatorioSaidas(this.confirma, this.idMedium, 
            this.codperiodo, this.mes1, this.ano1, this.mes2, this.ano2);
        }


// TODO add your handling code here:
    }//GEN-LAST:event_btImprimirActionPerformed

    public void verificaQuantidade(){
        if(!labelCoroa.getText().equals("Corôas") && !labelMediuns.getText().equals("Médiuns") && !labelPeriodo.getText().equals("Período")){
            c = new Coroa();
            labelValor.setText(String.valueOf(c.quantRelatorioSaidas(this.confirma, this.idMedium, 
            this.codperiodo, this.mes1, this.ano1, this.mes2, this.ano2)));
        }
    }
    public void fechar(){
        this.setAutoRequestFocus(false);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DRelatorioCoroa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DRelatorioCoroa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DRelatorioCoroa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DRelatorioCoroa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DRelatorioCoroa dialog = new DRelatorioCoroa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btImprimir;
    private javax.swing.JComboBox<String> comboMediuns;
    private javax.swing.ButtonGroup groupCoroas;
    private javax.swing.ButtonGroup groupMedium;
    private javax.swing.ButtonGroup groupPeriodo;
    private javax.swing.JLabel labelCoroa;
    private javax.swing.JLabel labelFotoCoroa;
    private javax.swing.JLabel labelMediuns;
    private javax.swing.JLabel labelPeriodo;
    private javax.swing.JLabel labelPreQuantidade;
    private javax.swing.JLabel labelRegistros;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelValor;
    private javax.swing.JLabel labelVersao;
    private javax.swing.JPanel panelCoroas;
    private javax.swing.JPanel panelDown;
    private javax.swing.JPanel panelMediuns;
    private javax.swing.JPanel panelPeriodo;
    private javax.swing.JPanel panelTop;
    private javax.swing.JRadioButton radioConfirmados;
    private javax.swing.JRadioButton radioCorrente;
    private javax.swing.JRadioButton radioMEspecif;
    private javax.swing.JRadioButton radioNConfirmados;
    private javax.swing.JRadioButton radioPeriodo;
    private javax.swing.JRadioButton radioProximos;
    private javax.swing.JRadioButton radioTodosM;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtAnoLetivo;
    private javax.swing.JTextField txtCodMedium;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtMesAno1;
    private javax.swing.JTextField txtMesAno2;
    private javax.swing.JTextField txtMesAno3;
    // End of variables declaration//GEN-END:variables
}
