/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistejm.telas;

import br.com.sistejm.classes.Constances;
import br.com.sistejm.classes.Mediuns;
import br.com.sistejm.classes.Relatorios;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Michel
 */
public class DRelMediuns extends javax.swing.JDialog {
    
    private int ano;
    private int mensalidade;
    private int coroacao;
    private int orixas;
    private int endereco;
    private int telefone;
    
    Mediuns m;
    Calendar c;
    Relatorios r;

    public int getCoroacao() {
        return coroacao;
    }

    public void setCoroacao(int coroacao) {
        this.coroacao = coroacao;
    }

    public int getEndereco() {
        return endereco;
    }

    public void setEndereco(int endereco) {
        this.endereco = endereco;
    }

    public int getTelefone() {
        return telefone;
    }

    public void setTelefone(int telefone) {
        this.telefone = telefone;
    }

    public int getAno() {
        return ano;
    }

    public void setAno(int ano) {
        this.ano = ano;
    }

    public int getMensalidade() {
        return mensalidade;
    }

    public void setMensalidade(int mensalidade) {
        this.mensalidade = mensalidade;
    }

    public int getOrixas() {
        return orixas;
    }

    public void setOrixas(int orixas) {
        this.orixas = orixas;
    }
    
    

    /**
     * Creates new form DRelMediuns
     */
    public DRelMediuns(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        preencheTitulo();
        ocultaTextMensal(false);
        preencheTabMediuns();
    }
    
    public void preencheTitulo(){
        this.setTitle(Constances.TITULO_DFICHASSMEDIUM);
    }
    
    public void ocultaTextMensal(boolean valor){
        txtAno.setText("");
        labelAno.setVisible(valor);
        txtAno.setVisible(valor);
    }
    
    public void preencheTabMediuns(){
        m = new Mediuns();
        m.preencheTabMedium(tabMediuns);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTop = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        btCancelar = new javax.swing.JButton();
        txtData = new javax.swing.JTextField();
        txtIdMedium = new javax.swing.JTextField();
        btImprimir = new javax.swing.JButton();
        panelDown = new javax.swing.JPanel();
        labelVersao = new javax.swing.JLabel();
        panelMedium = new javax.swing.JPanel();
        txtNomeMedium = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabMediuns = new javax.swing.JTable();
        radioTodos = new javax.swing.JRadioButton();
        radioMedEspecif = new javax.swing.JRadioButton();
        panelOutros = new javax.swing.JPanel();
        cMensalidades = new javax.swing.JCheckBox();
        cCoroacao = new javax.swing.JCheckBox();
        cOrixas = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        txtAno = new javax.swing.JTextField();
        labelAno = new javax.swing.JLabel();
        cTelefones = new javax.swing.JCheckBox();
        cEndereco = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelTop.setBackground(new java.awt.Color(255, 255, 255));
        panelTop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        labelTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelTitulo.setText("FICHAS DO MÉDIUM");

        btCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btCancelar.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/cancelar.png"))); // NOI18N
        btCancelar.setText("Sair");
        btCancelar.setToolTipText("Cancelar");
        btCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelar.setMaximumSize(new java.awt.Dimension(51, 43));
        btCancelar.setMinimumSize(new java.awt.Dimension(51, 43));
        btCancelar.setPreferredSize(new java.awt.Dimension(51, 43));
        btCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        txtData.setEditable(false);

        txtIdMedium.setEditable(false);

        btImprimir.setBackground(new java.awt.Color(255, 255, 255));
        btImprimir.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        btImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/print.png"))); // NOI18N
        btImprimir.setText("Imprimir");
        btImprimir.setToolTipText("Imprimir");
        btImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btImprimir.setMaximumSize(new java.awt.Dimension(51, 43));
        btImprimir.setMinimumSize(new java.awt.Dimension(51, 43));
        btImprimir.setPreferredSize(new java.awt.Dimension(51, 43));
        btImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addGap(37, 37, 37)
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtData, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(txtIdMedium))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTopLayout.createSequentialGroup()
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdMedium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDown.setBackground(new java.awt.Color(255, 255, 255));
        panelDown.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        labelVersao.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        labelVersao.setText("SISTEJM - Versão 1.0 - Interna");

        javax.swing.GroupLayout panelDownLayout = new javax.swing.GroupLayout(panelDown);
        panelDown.setLayout(panelDownLayout);
        panelDownLayout.setHorizontalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDownLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVersao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDownLayout.setVerticalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelVersao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelMedium.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MÉDIUM", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 10), new java.awt.Color(0, 0, 204))); // NOI18N

        tabMediuns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabMediuns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMediunsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabMediuns);

        radioTodos.setSelected(true);
        radioTodos.setText("Todos");

        radioMedEspecif.setText("De um médium específico");

        javax.swing.GroupLayout panelMediumLayout = new javax.swing.GroupLayout(panelMedium);
        panelMedium.setLayout(panelMediumLayout);
        panelMediumLayout.setHorizontalGroup(
            panelMediumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMediumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMediumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMediumLayout.createSequentialGroup()
                        .addComponent(radioTodos)
                        .addGap(31, 31, 31)
                        .addComponent(radioMedEspecif)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtNomeMedium))
                .addContainerGap())
        );
        panelMediumLayout.setVerticalGroup(
            panelMediumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMediumLayout.createSequentialGroup()
                .addGroup(panelMediumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioTodos)
                    .addComponent(radioMedEspecif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(txtNomeMedium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelOutros.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OUTROS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 10), new java.awt.Color(0, 0, 204))); // NOI18N

        cMensalidades.setText(" Mensalidades");
        cMensalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cMensalidadesActionPerformed(evt);
            }
        });

        cCoroacao.setText(" Histórico de coroação");
        cCoroacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCoroacaoActionPerformed(evt);
            }
        });

        cOrixas.setText(" Orixás e entidades divinas");
        cOrixas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cOrixasActionPerformed(evt);
            }
        });

        jCheckBox3.setText(" Atividades e colaborações");
        jCheckBox3.setEnabled(false);

        labelAno.setText("Ano:");

        cTelefones.setText(" Telefones");
        cTelefones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTelefonesActionPerformed(evt);
            }
        });

        cEndereco.setText(" Endereço");
        cEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cEnderecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOutrosLayout = new javax.swing.GroupLayout(panelOutros);
        panelOutros.setLayout(panelOutrosLayout);
        panelOutrosLayout.setHorizontalGroup(
            panelOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOutrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cCoroacao)
                    .addComponent(cOrixas)
                    .addComponent(jCheckBox3)
                    .addGroup(panelOutrosLayout.createSequentialGroup()
                        .addComponent(cMensalidades)
                        .addGap(29, 29, 29)
                        .addComponent(labelAno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cTelefones)
                    .addComponent(cEndereco))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOutrosLayout.setVerticalGroup(
            panelOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOutrosLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(cEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cTelefones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cMensalidades)
                    .addComponent(labelAno)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cCoroacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cOrixas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMedium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelOutros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMedium, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelOutros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        fechar();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed

        r = new Relatorios();
        
        r.relatorioFichaMedium(Integer.valueOf(txtIdMedium.getText()), 0, 0, 0, 0, 0, 0);
//        r.relatorioFichaMedium(Integer.valueOf(txtIdMedium.getText()), ano, ano, ano, ano, ERROR, ABORT);

//relatorioSaidas(String confirmado, int idmedium, int periodo, int mes1, int ano1, int mes2, int ano2)        
        
// relatorioMensalidade(String tipo, int idmedium, int periodo, int mes1, int ano1, int mes2, int ano2)
//tipo analitico // periodo 1

    }//GEN-LAST:event_btImprimirActionPerformed

    private void cMensalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cMensalidadesActionPerformed

        if(cMensalidades.isSelected()){
            this.mensalidade = 1;
            ocultaTextMensal(true);
            txtAno.requestFocus();
        }else{
            this.mensalidade = 0;
            ocultaTextMensal(false);
        }

    }//GEN-LAST:event_cMensalidadesActionPerformed

    private void cCoroacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCoroacaoActionPerformed

        if(cCoroacao.isSelected()){
            this.coroacao = 1;
        }else{
            this.coroacao = 0;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cCoroacaoActionPerformed

    private void cOrixasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cOrixasActionPerformed
        if(cOrixas.isSelected()){
            this.orixas = 1;
        }else{
            this.orixas = 0;
        }
    }//GEN-LAST:event_cOrixasActionPerformed

    private void cEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cEnderecoActionPerformed
        if(cEndereco.isSelected()){
            this.endereco = 1;
        }else{
            this.endereco = 0;
        }
    }//GEN-LAST:event_cEnderecoActionPerformed

    private void cTelefonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTelefonesActionPerformed
        if(cTelefones.isSelected()){
            this.telefone = 1;
        }else{
            this.telefone = 0;
        }
    }//GEN-LAST:event_cTelefonesActionPerformed

    private void tabMediunsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMediunsMouseClicked
        String nomeMedium = String.valueOf(tabMediuns.getValueAt(tabMediuns.getSelectedRow(), 0));
        txtNomeMedium.setText(nomeMedium.toUpperCase());
        
    }//GEN-LAST:event_tabMediunsMouseClicked

    public void fechar(){
        this.setAutoRequestFocus(false);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DRelMediuns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DRelMediuns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DRelMediuns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DRelMediuns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DRelMediuns dialog = new DRelMediuns(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btImprimir;
    private javax.swing.JCheckBox cCoroacao;
    private javax.swing.JCheckBox cEndereco;
    private javax.swing.JCheckBox cMensalidades;
    private javax.swing.JCheckBox cOrixas;
    private javax.swing.JCheckBox cTelefones;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAno;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelVersao;
    private javax.swing.JPanel panelDown;
    private javax.swing.JPanel panelMedium;
    private javax.swing.JPanel panelOutros;
    private javax.swing.JPanel panelTop;
    private javax.swing.JRadioButton radioMedEspecif;
    private javax.swing.JRadioButton radioTodos;
    private javax.swing.JTable tabMediuns;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtIdMedium;
    private javax.swing.JTextField txtNomeMedium;
    // End of variables declaration//GEN-END:variables
}
