/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistejm.telas;

import br.com.sistejm.classes.Agendamento;
import br.com.sistejm.classes.Configuracoes;
import br.com.sistejm.classes.Relatorios;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JTextField;

/**
 *
 * @author Michel
 */
public class DRelAgendamento extends javax.swing.JDialog {

    Agendamento at;
    Configuracoes config;
    Relatorios rel;
    Calendar cal;
    Date d;

    
    public int pago;
    public int baixado;
    public int consultor;
    public String dataInicial;
    public String dataFinal;

    public int getPago() {
        return pago;
    }

    public void setPago(int pago) {
        this.pago = pago;
    }

    public int getBaixado() {
        return baixado;
    }

    public void setBaixado(int baixado) {
        this.baixado = baixado;
    }

    public int getConsultor() {
        return consultor;
    }

    public void setConsultor(int consultor) {
        this.consultor = consultor;
    }
    /**
     * Creates new form DRelAgendamento
     */
    public DRelAgendamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ativaPanelData(true);
        preencheTabela();
        alimentaVar();
    }
    
    public void alimentaVar(){
        this.pago = 9;
        this.consultor = 9;
        this.baixado = 9;
        this.dataInicial = "sem data";
        this.dataFinal = "sem data";
    }
    public void preencheTabelaGeral(){
        at = new Agendamento();
        at.preencheTabAgend(tabelaRelConsulta);
    }
    
    public void ativaPanelData(boolean valor){
        panelPeriodo.setEnabled(valor);
    }

    public void preencheTabela(){
        at = new Agendamento();
        at.preencheTabAgend(tabelaRelConsulta);
    }
   
    public void direcionaDataInicial(){
        txtDataInicial.requestFocus();
    }
    
    public void fechar(){
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        groupPagos = new javax.swing.ButtonGroup();
        groupPeriodo = new javax.swing.ButtonGroup();
        groupBaixa = new javax.swing.ButtonGroup();
        panelDown = new javax.swing.JPanel();
        labelVersao = new javax.swing.JLabel();
        panelTop = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        btImprimir = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        panelPeriodo = new javax.swing.JPanel();
        labelAte = new javax.swing.JLabel();
        labelPeriodo = new javax.swing.JLabel();
        radioHoje = new javax.swing.JRadioButton();
        radioOutras = new javax.swing.JRadioButton();
        txtDataInicial = new javax.swing.JTextField();
        txtDataFinal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaRelConsulta = new javax.swing.JTable();
        panelPagos = new javax.swing.JPanel();
        rPagos = new javax.swing.JRadioButton();
        rNaoPagos = new javax.swing.JRadioButton();
        rTodosPagos = new javax.swing.JRadioButton();
        panelConsultores = new javax.swing.JPanel();
        cCab = new javax.swing.JRadioButton();
        cExu = new javax.swing.JRadioButton();
        cTodo = new javax.swing.JRadioButton();
        panelBaixa = new javax.swing.JPanel();
        rTodosBaixa = new javax.swing.JRadioButton();
        rNaoBaixa = new javax.swing.JRadioButton();
        cBaixa = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelDown.setBackground(new java.awt.Color(255, 255, 255));
        panelDown.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        labelVersao.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        labelVersao.setText("SISTEJM - Versão 1.0 - Interna");

        javax.swing.GroupLayout panelDownLayout = new javax.swing.GroupLayout(panelDown);
        panelDown.setLayout(panelDownLayout);
        panelDownLayout.setHorizontalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDownLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVersao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDownLayout.setVerticalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelVersao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelTop.setBackground(new java.awt.Color(255, 255, 255));
        panelTop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTitulo.setText("Relatório de Agendamento | Atendimento");

        btImprimir.setBackground(new java.awt.Color(255, 255, 255));
        btImprimir.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        btImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/print.png"))); // NOI18N
        btImprimir.setText("Imprimir");
        btImprimir.setToolTipText("Imprimir");
        btImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });

        btSair.setBackground(new java.awt.Color(255, 255, 255));
        btSair.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistejm/images/cancelar.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.setToolTipText("Sair");
        btSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelPeriodo.setBackground(new java.awt.Color(255, 255, 255));
        panelPeriodo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "   PERÍODO   ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 10), new java.awt.Color(0, 0, 153))); // NOI18N

        labelAte.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelAte.setText("até");

        labelPeriodo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelPeriodo.setText("De");

        radioHoje.setBackground(new java.awt.Color(255, 255, 255));
        groupPeriodo.add(radioHoje);
        radioHoje.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        radioHoje.setText("  Hoje");
        radioHoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioHojeActionPerformed(evt);
            }
        });

        radioOutras.setBackground(new java.awt.Color(255, 255, 255));
        groupPeriodo.add(radioOutras);
        radioOutras.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        radioOutras.setSelected(true);
        radioOutras.setText("  Outras datas (dd/mm/aaaa)");
        radioOutras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioOutrasActionPerformed(evt);
            }
        });

        txtDataInicial.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtDataInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDataInicialKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDataInicialKeyReleased(evt);
            }
        });

        txtDataFinal.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtDataFinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDataFinalKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelPeriodoLayout = new javax.swing.GroupLayout(panelPeriodo);
        panelPeriodo.setLayout(panelPeriodoLayout);
        panelPeriodoLayout.setHorizontalGroup(
            panelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPeriodoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPeriodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(labelAte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPeriodoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioHoje)
                .addGap(18, 18, 18)
                .addComponent(radioOutras)
                .addGap(21, 21, 21))
        );
        panelPeriodoLayout.setVerticalGroup(
            panelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPeriodoLayout.createSequentialGroup()
                .addGroup(panelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioHoje)
                    .addComponent(radioOutras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAte)
                    .addComponent(labelPeriodo)
                    .addComponent(txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "   PRÉ-VISUALIZAÇÃO   ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 10), new java.awt.Color(0, 0, 153))); // NOI18N

        tabelaRelConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaRelConsulta);

        panelPagos.setBackground(new java.awt.Color(255, 255, 255));
        panelPagos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "   PAGOS   ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 10), new java.awt.Color(0, 0, 153))); // NOI18N

        rPagos.setBackground(new java.awt.Color(255, 255, 255));
        groupPagos.add(rPagos);
        rPagos.setText(" Sim");
        rPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rPagosActionPerformed(evt);
            }
        });

        rNaoPagos.setBackground(new java.awt.Color(255, 255, 255));
        groupPagos.add(rNaoPagos);
        rNaoPagos.setText(" Não");
        rNaoPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rNaoPagosActionPerformed(evt);
            }
        });

        rTodosPagos.setBackground(new java.awt.Color(255, 255, 255));
        groupPagos.add(rTodosPagos);
        rTodosPagos.setSelected(true);
        rTodosPagos.setText(" Todos");
        rTodosPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rTodosPagosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPagosLayout = new javax.swing.GroupLayout(panelPagos);
        panelPagos.setLayout(panelPagosLayout);
        panelPagosLayout.setHorizontalGroup(
            panelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rPagos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rNaoPagos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rTodosPagos)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelPagosLayout.setVerticalGroup(
            panelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPagosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rPagos)
                    .addComponent(rNaoPagos)
                    .addComponent(rTodosPagos)))
        );

        panelConsultores.setBackground(new java.awt.Color(255, 255, 255));
        panelConsultores.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "   CONSULTORES   ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 10), new java.awt.Color(0, 0, 153))); // NOI18N

        cCab.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(cCab);
        cCab.setText(" Caboclo");
        cCab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCabActionPerformed(evt);
            }
        });

        cExu.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(cExu);
        cExu.setText(" Exu");
        cExu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cExuActionPerformed(evt);
            }
        });

        cTodo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(cTodo);
        cTodo.setSelected(true);
        cTodo.setText(" Todos");
        cTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConsultoresLayout = new javax.swing.GroupLayout(panelConsultores);
        panelConsultores.setLayout(panelConsultoresLayout);
        panelConsultoresLayout.setHorizontalGroup(
            panelConsultoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cCab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cExu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cTodo)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        panelConsultoresLayout.setVerticalGroup(
            panelConsultoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cCab)
                .addComponent(cExu)
                .addComponent(cTodo))
        );

        panelBaixa.setBackground(new java.awt.Color(255, 255, 255));
        panelBaixa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "   BAIXADO   ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 10), new java.awt.Color(0, 0, 204))); // NOI18N

        rTodosBaixa.setBackground(new java.awt.Color(255, 255, 255));
        groupBaixa.add(rTodosBaixa);
        rTodosBaixa.setSelected(true);
        rTodosBaixa.setText(" Todos");
        rTodosBaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rTodosBaixaActionPerformed(evt);
            }
        });

        rNaoBaixa.setBackground(new java.awt.Color(255, 255, 255));
        groupBaixa.add(rNaoBaixa);
        rNaoBaixa.setText(" Não");
        rNaoBaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rNaoBaixaActionPerformed(evt);
            }
        });

        cBaixa.setBackground(new java.awt.Color(255, 255, 255));
        groupBaixa.add(cBaixa);
        cBaixa.setText(" Sim");
        cBaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBaixaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBaixaLayout = new javax.swing.GroupLayout(panelBaixa);
        panelBaixa.setLayout(panelBaixaLayout);
        panelBaixaLayout.setHorizontalGroup(
            panelBaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cBaixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rNaoBaixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rTodosBaixa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBaixaLayout.setVerticalGroup(
            panelBaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBaixaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelBaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBaixa)
                    .addComponent(rNaoBaixa)
                    .addComponent(rTodosBaixa)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelConsultores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(panelPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelConsultores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed
        rel = new Relatorios();
        config = new Configuracoes();

        if(txtDataInicial.getText().equals("")){
            this.dataInicial = "sem data";
        }else{
            this.dataInicial = config.retornaFormatoDataSQL(txtDataInicial.getText());
        }
        if(txtDataFinal.getText().equals("")){
            this.dataFinal = "sem data";
        }else{
            this.dataFinal = config.retornaFormatoDataSQL(txtDataFinal.getText());
        }
        
        rel.relTabAgend(this.dataInicial, this.dataFinal, this.pago, this.baixado, this.consultor);
//        rel.geraRelatorioAgendamento(this.getModelo(), valor, config.retornaFormatoDataSQL(txtDataInicial.getText()), config.retornaFormatoDataSQL(txtDataFinal.getText()), this.getOrdem());

    }//GEN-LAST:event_btImprimirActionPerformed

    private void txtDataInicialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataInicialKeyReleased

        if(txtDataInicial.getText().length() == 2){
            txtDataInicial.setText(txtDataInicial.getText() + "/");
        }
        if(txtDataInicial.getText().length() == 5){
            txtDataInicial.setText(txtDataInicial.getText() + "/");
        }
        if(txtDataInicial.getText().length() == 10){
            txtDataInicial.requestFocus();
            this.dataInicial = txtDataInicial.getText();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataInicialKeyReleased

    private void txtDataFinalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataFinalKeyReleased

        if(txtDataFinal.getText().length() == 2){
            txtDataFinal.setText(txtDataFinal.getText() + "/");
        }
        if(txtDataFinal.getText().length() == 5){
            txtDataFinal.setText(txtDataFinal.getText() + "/");
        }
        if(txtDataFinal.getText().length() == 10){
            this.dataFinal = txtDataFinal.getText();
            pesquisaPreRelatorio();
        }

    }//GEN-LAST:event_txtDataFinalKeyReleased

    private void txtDataInicialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataInicialKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtDataFinal.setText(txtDataInicial.getText());
            txtDataFinal.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataInicialKeyPressed

    private void radioOutrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioOutrasActionPerformed

        txtDataInicial.setText("");
        txtDataFinal.setText("");
        txtDataInicial.requestFocus();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_radioOutrasActionPerformed

    private void radioHojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioHojeActionPerformed

        config = new Configuracoes();
        
        txtDataInicial.setText(config.retornaData());
        txtDataFinal.setText(config.retornaData());

        pesquisaPreRelatorio();
        // TODO add your handling code here:
    }//GEN-LAST:event_radioHojeActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.fechar();
// TODO add your handling code here:
    }//GEN-LAST:event_btSairActionPerformed

    private void cCabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCabActionPerformed

        this.consultor = 1;

        pesquisaPreRelatorio();
        // TODO add your handling code here:
    }//GEN-LAST:event_cCabActionPerformed

    private void cExuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cExuActionPerformed

        this.consultor = 2;
        pesquisaPreRelatorio();
        // TODO add your handling code here:
    }//GEN-LAST:event_cExuActionPerformed

    private void cTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTodoActionPerformed
        this.consultor = 9;
        pesquisaPreRelatorio();
        // TODO add your handling code here:
    }//GEN-LAST:event_cTodoActionPerformed

    private void rTodosPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rTodosPagosActionPerformed
        this.pago = 9;
        pesquisaPreRelatorio();
        // TODO add your handling code here:
    }//GEN-LAST:event_rTodosPagosActionPerformed

    private void rTodosBaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rTodosBaixaActionPerformed
        this.baixado = 9;
        pesquisaPreRelatorio();
        // TODO add your handling code here:
    }//GEN-LAST:event_rTodosBaixaActionPerformed

    private void rPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rPagosActionPerformed

        this.pago = 1;
        pesquisaPreRelatorio();
        // TODO add your handling code here:
    }//GEN-LAST:event_rPagosActionPerformed

    private void rNaoPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rNaoPagosActionPerformed

        this.pago = 0;
        pesquisaPreRelatorio();
        // TODO add your handling code here:
    }//GEN-LAST:event_rNaoPagosActionPerformed

    private void cBaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBaixaActionPerformed

        this.baixado = 1;
        pesquisaPreRelatorio();
        // TODO add your handling code here:
    }//GEN-LAST:event_cBaixaActionPerformed

    private void rNaoBaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rNaoBaixaActionPerformed
        this.baixado = 0;
        pesquisaPreRelatorio();
        // TODO add your handling code here:
    }//GEN-LAST:event_rNaoBaixaActionPerformed

    
    public void pesquisaPreRelatorio(){
        at = new Agendamento();
        config = new Configuracoes();
        
        if(txtDataInicial.getText().equals("")){
            this.dataInicial = "sem data";
        }else{
            this.dataInicial = config.retornaFormatoDataSQL(txtDataInicial.getText());
        }
        if(txtDataFinal.getText().equals("")){
            this.dataFinal = "sem data";
        }else{
            this.dataFinal = config.retornaFormatoDataSQL(txtDataFinal.getText());
        }
        at.buscaTabAgend(tabelaRelConsulta, this.dataInicial, this.dataFinal, this.pago, this.baixado, this.consultor);

    }
    
    public void mascaraData(JTextField campo){
        if(campo.getText().length() == 2){
            campo.setText(campo.getText() + "/");
        }
        if(campo.getText().length() == 5){
            campo.setText(campo.getText() + "/");
        }        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DRelAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DRelAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DRelAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DRelAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DRelAgendamento dialog = new DRelAgendamento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btImprimir;
    private javax.swing.JButton btSair;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton cBaixa;
    private javax.swing.JRadioButton cCab;
    private javax.swing.JRadioButton cExu;
    private javax.swing.JRadioButton cTodo;
    private javax.swing.ButtonGroup groupBaixa;
    private javax.swing.ButtonGroup groupPagos;
    private javax.swing.ButtonGroup groupPeriodo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAte;
    private javax.swing.JLabel labelPeriodo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelVersao;
    private javax.swing.JPanel panelBaixa;
    private javax.swing.JPanel panelConsultores;
    private javax.swing.JPanel panelDown;
    private javax.swing.JPanel panelPagos;
    private javax.swing.JPanel panelPeriodo;
    private javax.swing.JPanel panelTop;
    private javax.swing.JRadioButton rNaoBaixa;
    private javax.swing.JRadioButton rNaoPagos;
    private javax.swing.JRadioButton rPagos;
    private javax.swing.JRadioButton rTodosBaixa;
    private javax.swing.JRadioButton rTodosPagos;
    private javax.swing.JRadioButton radioHoje;
    private javax.swing.JRadioButton radioOutras;
    private javax.swing.JTable tabelaRelConsulta;
    private javax.swing.JTextField txtDataFinal;
    private javax.swing.JTextField txtDataInicial;
    // End of variables declaration//GEN-END:variables
}
