/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistejm.telas;

import br.com.sistejm.classes.Configuracoes;

/**
 *
 * @author Michel
 */
public class DSelecionaOpMedium extends javax.swing.JDialog {
    
    private int codUser;
    private String usuario;
    TelaInicial principal;
    DialogMediuns dmed;
    Configuracoes config;
    DMedium med;
    DMediumEspiritos mede;
    DDatasMedium datam;

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public int getCodUser() {
        return codUser;
    }

    public void setCodUser(int codUser) {
        this.codUser = codUser;
    }
    
    

    /**
     * Creates new form DSekecionaOpMedium
     */
    public DSelecionaOpMedium(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        preencheLabel();
    }
    
    public void preencheLabel(){
        labelTitulo.setText("Selecione a operação com médiuns");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        panelDown = new javax.swing.JPanel();
        labelVersao = new javax.swing.JLabel();
        panelTop = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelSeleciona = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        radioManterMedium = new javax.swing.JRadioButton();
        radioManterDados = new javax.swing.JRadioButton();
        radioManterEntidades = new javax.swing.JRadioButton();
        radioManterDatas = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelDown.setBackground(new java.awt.Color(255, 255, 255));
        panelDown.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        labelVersao.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        labelVersao.setText("SISTEJM - Versão 1.0 - Interna");

        javax.swing.GroupLayout panelDownLayout = new javax.swing.GroupLayout(panelDown);
        panelDown.setLayout(panelDownLayout);
        panelDownLayout.setHorizontalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDownLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVersao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDownLayout.setVerticalGroup(
            panelDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelVersao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelTop.setBackground(new java.awt.Color(255, 255, 255));
        panelTop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        labelTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelTitulo.setText("jLabel1");

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        labelSeleciona.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelSeleciona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSeleciona.setText("Selecione a operação:");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        buttonGroup.add(radioManterMedium);
        radioManterMedium.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        radioManterMedium.setText("Cadastrar/ Excluir médium");
        radioManterMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioManterMediumActionPerformed(evt);
            }
        });

        buttonGroup.add(radioManterDados);
        radioManterDados.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        radioManterDados.setText("Pesquisar, Atualizar as informações do médium");
        radioManterDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioManterDadosActionPerformed(evt);
            }
        });

        buttonGroup.add(radioManterEntidades);
        radioManterEntidades.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        radioManterEntidades.setText("Incluir Orixás, Entidades etc. do médium");
        radioManterEntidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioManterEntidadesActionPerformed(evt);
            }
        });

        buttonGroup.add(radioManterDatas);
        radioManterDatas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        radioManterDatas.setText("Verificar data de saídas, batismo etc do médium");
        radioManterDatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioManterDatasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioManterMedium)
                    .addComponent(radioManterDados)
                    .addComponent(radioManterEntidades)
                    .addComponent(radioManterDatas))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioManterMedium)
                .addGap(18, 18, 18)
                .addComponent(radioManterDados)
                .addGap(18, 18, 18)
                .addComponent(radioManterEntidades)
                .addGap(18, 18, 18)
                .addComponent(radioManterDatas)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDown, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelSeleciona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSeleciona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(panelDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioManterMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioManterMediumActionPerformed

        principal = new TelaInicial();
        med = new DMedium(principal, false);
        med.setLocationRelativeTo(med);
        med.setTitle("Médiuns");
        med.recebeUsuario(codUser);
        med.setVisible(true);
        config = new Configuracoes();
        config.gravaAtividades("Médiuns", this.usuario, "Abertura Cadastro ou exclusão de médiuns");
//        fechar();
        // TODO add your handling code here:
    }//GEN-LAST:event_radioManterMediumActionPerformed

    private void radioManterDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioManterDadosActionPerformed
        principal = new TelaInicial();
        dmed = new DialogMediuns(principal, false);
        dmed.setLocationRelativeTo(dmed);
        dmed.setTitle("Médiuns - Endereço | Contato");
        dmed.recebeUsuario(codUser);
        dmed.setVisible(true);
        config = new Configuracoes();
        config.gravaAtividades("Médiuns", this.usuario, "Abertura Pesquisa e atualização médiuns");
//        fechar();        
// TODO add your handling code here:
    }//GEN-LAST:event_radioManterDadosActionPerformed

    private void radioManterEntidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioManterEntidadesActionPerformed
        principal = new TelaInicial();
        mede = new DMediumEspiritos(principal, false);
        mede.setLocationRelativeTo(mede);
        mede.setTitle("Médiuns");
        mede.recebeUsuario(codUser);
        mede.setVisible(true);
        config = new Configuracoes();
        config.gravaAtividades("Médiuns", this.usuario, "Abertura de atualização de entidade dos médiuns");
//        fechar();
        // TODO add your handling code here:
    }//GEN-LAST:event_radioManterEntidadesActionPerformed

    private void radioManterDatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioManterDatasActionPerformed
        principal = new TelaInicial();
        datam = new DDatasMedium(principal, false);
        datam.setLocationRelativeTo(datam);
        datam.setTitle("Médiuns");
        datam.recebeUsuario(codUser);
        datam.setVisible(true);
        config = new Configuracoes();
        config.gravaAtividades("Médiuns", this.usuario, "Abertura de datas dos médiuns");
        // TODO add your handling code here:
    }//GEN-LAST:event_radioManterDatasActionPerformed

    public void recebeUsuario(int codUser, String nomeUsuario){
        this.setCodUser(codUser);
        this.setUsuario(nomeUsuario);
    }
    public void fechar(){
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DSelecionaOpMedium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DSelecionaOpMedium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DSelecionaOpMedium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DSelecionaOpMedium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DSelecionaOpMedium dialog = new DSelecionaOpMedium(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelSeleciona;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelVersao;
    private javax.swing.JPanel panelDown;
    private javax.swing.JPanel panelTop;
    private javax.swing.JRadioButton radioManterDados;
    private javax.swing.JRadioButton radioManterDatas;
    private javax.swing.JRadioButton radioManterEntidades;
    private javax.swing.JRadioButton radioManterMedium;
    // End of variables declaration//GEN-END:variables
}
